### ISSUE TITLE
方便请教下 asymmetrics和正常的区别是?

### ISSUE THREAD

**Issue by liangzh-404** [whyt-byte/Blue-Topaz_Obsidian-css#1]
现在看到的是edit模式下可视化了引用~

**Comment by whyt-byte** [comment]
都加了可视化引用。不对称那款的区别是：明亮模式的标题不再隐藏“#”，而且标题颜色做了渐变。主要是因为现阶段隐藏“#”会造成光标错位，Asymmetric算是对此的折中方案

**Comment by whyt-byte** [comment]
我在论坛上有图，见：https://forum.obsidian.md/uploads/default/original/2X/4/4f71fd962fa6d6befdc479c87527afdefb2b345c.png
