### ISSUE TITLE
代码块的换行问题

### ISSUE THREAD

**Issue by ryanliag** [whyt-byte/Blue-Topaz_Obsidian-css#10]
例如我使用的是java语言，在编辑模式下的代码块注释部分显示的是带换行符的文本，但是到了预览模式就合并为一行了。
![image](https://user-images.githubusercontent.com/35890564/99253790-54c8bf80-284c-11eb-8979-ffb0c645d2cf.png)
![image](https://user-images.githubusercontent.com/35890564/99253793-572b1980-284c-11eb-9652-4b9f0238076a.png)

**Comment by whyt-byte** [comment]
你使用的应该不是最新版，这个问题已经修正，请更新新版，新版新加了“代码框显示代码语言名称”的特性。最新版的是20201114，写在开头注释里，可以看一下是否是新版。css会随着obsidian软件更新发布新版，也请继续使用。

![image](https://user-images.githubusercontent.com/72023275/99367430-e68c0780-28f4-11eb-87d7-23596fb11017.png)
