### ISSUE TITLE
代码块中注释颜色太浅

### ISSUE THREAD

**Issue by DuZzzs** [whyt-byte/Blue-Topaz_Obsidian-css#101]
您好，使用的是从这里下载的最新版主题，在代码块中注释颜色太浅，请问如何修改呢？谢谢
![image](https://user-images.githubusercontent.com/46736075/141120468-7ca369a6-3eef-4e0c-a867-d1c5fafde672.png)

**Comment by cumany** [comment]
代码块 高亮建议用 Editor Syntax Highlight 和 codemirror option 插件
就可以在 style settings 插件中调整 高亮风格模式。

**Comment by DuZzzs** [comment]
好的，谢谢  @cumany

**Comment by whyt-byte** [comment]
已做调整，请更新主题查看
