### ISSUE TITLE
RTL support in line list/box style

### ISSUE THREAD

**Issue by Alexnoj** [whyt-byte/Blue-Topaz_Obsidian-css#102]
Can u please make your skin support RTL language?

Thanks!

**Comment by whyt-byte** [comment]
I wonder which one you want: 
1. the theme just to support the list and code/quote box for RTL languages, 
2. or all texts to be RTL.

**Comment by Alexnoj** [comment]
for text I use RTL plugin.

If its possible RTL support for list bullet connecting edit/preview mode.

**Comment by Alexnoj** [comment]
for text I use RTL plugin.

If its possible RTL support for list bullet connecting edit/preview mode.

**Comment by whyt-byte** [comment]
Thank you for your information. Now I know what I should focus on. I will think about how to support the RTL plugin.

**Comment by whyt-byte** [comment]
Fixed
