### ISSUE TITLE
空格宽度问题

### ISSUE THREAD

**Issue by squareyk** [whyt-byte/Blue-Topaz_Obsidian-css#107]
obsidian版本：最新
theme版本：最新
font: Source Han Sans HW （等宽字体）
不使用任何主题，编辑模式下表单整齐：
![Inked屏幕截图 2021-11-18 123841](https://user-images.githubusercontent.com/25664177/142353414-b70c907a-5c28-47d0-b758-1af70e7d257d.jpg)

使用本主题，编辑模式下表单不整齐：
![Inked屏幕截图 2021-11-18 124147](https://user-images.githubusercontent.com/25664177/142353596-9d2b6a83-2ac3-4261-92d9-cd4ca59c6dcc.jpg)

```
| 十点十分           | 士大夫方法是 |
|:------------------ | ------------ |
| 士大夫胜多负少     | 广泛的       |
| 但是发射           | 豆腐干反对   |
|                    |              |
| 撒旦撒             |              |
| 实打实的都是发生过 |              |
```
好像chrome浏览器也渲染不整齐
问题：是不是空格的问题，怎么变得整齐？

**Comment by whyt-byte** [comment]
我没有复现出全部对齐的样子。
默认主题，默认字体（Source Code Pro， monospace）
![image](https://user-images.githubusercontent.com/72023275/142632211-62d46460-e78c-482c-af17-e892a4b6880f.png)

Fira Code
![image](https://user-images.githubusercontent.com/72023275/142632322-dd576d45-6592-486e-9a85-0f6b59c42208.png)

Microsoft Yahei Mono
![image](https://user-images.githubusercontent.com/72023275/142632568-513885ef-3a70-484d-bb86-2d0116572812.png)

可能还需要些时间研究一下，或者你能提供更多的一些信息吗？比如用没有表格相关的插件之类的

**Comment by squareyk** [comment]
> 是不是空格的问题，怎么变得整齐？

使用的的插件是advanced tables(可以直接在community plugins里面搜到)，
插件是默认打开自动填充空格的选项：
![屏幕截图 2021-11-20 074648](https://user-images.githubusercontent.com/25664177/142704974-03a2252c-657c-4f46-a8c2-4cf4805678b0.png)

关于类似情况也有人给这个仓库[提问](https://github.com/tgrosinger/advanced-tables-obsidian/issues/106)过。给的答复是使用等宽字体，我用的思源黑体HW。

问题：在默认主题是整齐的，开启本主题不整齐？

ps：其实这是美观问题，无伤大雅，还是感谢回答，你要是复现要安装等宽字体，并使用

**Comment by cumany** [comment]
字体：LXGW WenKai
主题：Blue Topaz


> > 是不是空格的问题，怎么变得整齐？
> 
> 使用的的**插件是advanced tables**(可以直接在community plugins里面搜到)， 插件是默认打开自动填充空格的选项： ![屏幕截图 2021-11-20 074648](https://user-images.githubusercontent.com/25664177/142704974-03a2252c-657c-4f46-a8c2-4cf4805678b0.png)
> 
> 关于类似情况也有人给这个仓库[提问](https://github.com/tgrosinger/advanced-tables-obsidian/issues/106)过。**给的答复是使用等宽字体，我用的思源黑体HW。**
> 
> **问题：在默认主题是整齐的，开启本主题不整齐？**
> 
> **ps：其实这是美观问题，无伤大雅，还是感谢回答，你要是复现要安装等宽字体，并使用** **关于中文等宽字体：**[看这里](https://moe.best/gotagota/vscode-monospaced.html)， [还有这里](https://leonvision.online/technology/monospace-chinese-font-family/)

我用的字体是LXGW WenKai 也是Blue topaz 推荐的字体。
我发现存在你说的不对齐的情况，但进行这样设置后就会对齐。
安装codemirror 插件 
1.如果开启渲染，如图设置
![image](https://user-images.githubusercontent.com/42957010/142715278-1e72eccc-f166-4a12-8cc8-3b6830f94902.png)
编辑状态是这样的
![image](https://user-images.githubusercontent.com/42957010/142715292-d06e7c1e-8398-4408-b7e5-3810fc96bc32.png)
2.关闭渲染 如图设置
![image](https://user-images.githubusercontent.com/42957010/142715309-ad3eb4cb-4b94-4ee7-9df4-86dde99ca24c.png)
编辑状态表格也是自动对齐的
![image](https://user-images.githubusercontent.com/42957010/142715318-6d708613-e670-4bc3-a13a-086a44e155cb.png)

不知能否解决你的问题。

**Comment by squareyk** [comment]
> 
感谢答复，安装了codemirror 插件，同样设置，没用，

在table整齐与Blue Topaz主题之间我选择主题，哈哈，我很喜欢这款蓝色主题，编辑页面是自己看的无所谓了，我关问题了

**Comment by whyt-byte** [comment]
> > 
> 
> 感谢答复，安装了codemirror 插件，同样设置，没用，
> 
> 在table整齐与Blue Topaz主题之间我选择主题，哈哈，我很喜欢这款蓝色主题，编辑页面是自己看的无所谓了，我关问题了

感谢你喜欢这个主题。后续我会再测试一下表格（上面我发的图里也都用的等宽字体，但是都没有对齐），看看有没有别的方式。另外，如果你没有安装style settings插件，强烈建议安装一下，它可以极大增强主题的使用体验。

**Comment by squareyk** [comment]
谢谢，安装了，加群了，群里人很好，回复很及时！
