### ISSUE TITLE
当列表和选择框混合使用时缩进错误

### ISSUE THREAD

**Issue by 527846952** [whyt-byte/Blue-Topaz_Obsidian-css#11]
-  [ ] listitem and checkbox
	-  [ ] listitem and checkbox
-  [ ] listitem and checkbox
	-  listitem(这种情况下缩进不对)
- listItem
	- listItem
		- listItem

**Comment by 527846952** [comment]
.markdown-preview-view ul > li.task-list-item {
  list-style: none;
  text-indent: 0em;
}
追加以上定义可以修复排版错误

**Comment by whyt-byte** [comment]
好的，收到，谢谢反馈，而且连解决方案都给了😻

**Comment by whyt-byte** [comment]
> * [ ]  listitem and checkbox
>   
>   * [ ]  listitem and checkbox
> * [ ]  listitem and checkbox
>   
>   * listitem(这种情况下缩进不对)
> * listItem
>   
>   * listItem
>     
>     * listItem

麻烦提供一下图片，我这边测试没有看到问题（倒是发现了checkbox没有跟竖线对齐）

![image](https://user-images.githubusercontent.com/72023275/99528090-b87ff380-29d8-11eb-9e90-064e57adc419.png)
