### ISSUE TITLE
两段引用之间没断开

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#12]
![Snipaste_2020-11-19_13-43-56](https://user-images.githubusercontent.com/56058332/99626694-bae05d00-2a6d-11eb-9340-d1933b9db6e3.png)

引用的是不同的两部分内容，在预览模式下竖线连在一起了

**Comment by whyt-byte** [comment]
谢谢反馈，已修复
