### ISSUE TITLE
CSS to Change italic color in editor

### ISSUE THREAD

**Issue by csss1234** [whyt-byte/Blue-Topaz_Obsidian-css#120]
I know some things changed with the most recent versions of obsidian, I'm on 0.13.4, not using the experimental Live Preview.

this CSS is working for me to change color of italics in preview mode, but nothing I've tried is working in editor mode.

```
/* of italics in Preview  all notes in a vault */
.markdown-preview-section em {
    color: #DDDDDD !important;
	font-style: !important;
}
```

**Comment by whyt-byte** [comment]
You can use the Style Settings plugin to adjust the italic color easily. 

Alternatively, the following code may be helpful to get the color you like.
```css
.theme-light {
 --accent-em: ;
}
.theme-dark {
 --accent-em: ;
}
```
