### ISSUE TITLE
缩进问题

### ISSUE THREAD

**Issue by jasonlove521** [whyt-byte/Blue-Topaz_Obsidian-css#121]
1. Articles.
1.  Book chapters assigned for the day.
2.  Re-reading past notes.
我在文档里写了这样的文档，然后编译成了这样的
![image](https://user-images.githubusercontent.com/42378479/142791257-4da1de02-4628-48af-9701-ac4d5619d415.png)
怎么解决这个问题

**Comment by whyt-byte** [comment]
没看懂你要做什么，也没给出问题，我没有办法回答。

请详细描述你的问题。

**Comment by whyt-byte** [comment]
已在群中解决
