### ISSUE TITLE
能否把代码块的显示不做换行处理

### ISSUE THREAD

**Issue by simowce** [whyt-byte/Blue-Topaz_Obsidian-css#122]
目前这个主题在代码块的显示效果是这样的：
![image](https://user-images.githubusercontent.com/8957416/143446821-b5d4d3be-9268-4738-9647-d3a2198371b2.png)
也就是如果代码内容超过一定的宽度以后，会被自动换行，我其实不是很喜欢这种效果，我希望是无论一行代码无论多少个字符都能够在一行内显示，如果过长可以有一个水平滚动条，不知道这个效果能不能实现呢？

**Comment by whyt-byte** [comment]
你可能使用的主题版本比较低，请尝试更新主题

**Comment by whyt-byte** [comment]
![image](https://user-images.githubusercontent.com/72023275/143451837-9cc15e01-7cbd-4e06-9312-bd5f82f4b443.png)
主题默认设置如上。

看你截图颜色可能使用了Codemirror Options，请在Style Settings插件内设置Codemirror Options的换行选项
![image](https://user-images.githubusercontent.com/72023275/143452087-b5ff181e-c2fa-4a7b-9874-aeb584fd0b88.png)

**Comment by twinkle255** [comment]
不知道你解决这个问题了没有，我折腾好久，最后发现添加一个CSS代码片段就行了。
[滚动条问题解决方法.md](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/files/9033278/default.md)
这是代码，创建CSS片段以后放入snippets文件夹然后再obsidian内启用就可以解决了

**Comment by seanutf** [comment]
Obsidian国外社区也有个可行的方法,亲测有效,不过仅支持阅读模式, 这种功能还是希望官方能早些支持吧, 明明对普通用户来讲就是一个选项的问题, 却要搞CSS配置才能搞定,用户体验垃圾啊
https://forum.obsidian.md/t/disable-word-wrap-for-code-blocks/13210/8

**Comment by cumany** [comment]
style setting  2.3.9.1 可以设置代码块是否换行。  也可以在 yaml区域声明 cssclass: "code-wrap"  当前文档的代码块换行。

**Comment by Willingchan** [comment]
> 不知道你解决这个问题了没有，我折腾好久，最后发现添加一个CSS代码片段就行了。 [滚动条问题解决方法.md](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/files/9033278/default.md) 这是代码，创建CSS片段以后放入snippets文件夹然后再obsidian内启用就可以解决了

为什么我用着不行啊，能具体一点吗

**Comment by sjhsbhqf** [comment]
如果你是使用style setting 插件。

里面的Blue Topaz外观样式，这样添加滚动条，也即不换行处理。
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/41407099/040f88df-43f1-493a-9358-06858efe551f)

如果你是使用minimal样式，如下操作
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/41407099/c871672d-36b8-4ee3-a4ee-31d214aa23d9)
