### ISSUE TITLE
Live Preview Mode - Quotes not rendered properly

### ISSUE THREAD

**Issue by Sachin-12** [whyt-byte/Blue-Topaz_Obsidian-css#123]
![image](https://user-images.githubusercontent.com/24960422/143659356-8cfa12e3-8ace-4bfb-8d28-d78814a29f29.png)
Hi. In Live Preview mode, Using quotes `> This is a quote` is rendered as shown above.

**Comment by whyt-byte** [comment]
It's fixed, thanks for telling me! Please update the theme.

By the way, I am sorry that I haven't tested and optimised the Live Preview mode since the Live Preview hasn't been finished. So if there are still such problems that bother you, please feel free to contact me. Thank you!

**Comment by Sachin-12** [comment]
Totally understandable and sorry is a big word when it is an open source. A big thanks for such a quick fix. The theme is awesome.
