### ISSUE TITLE
Bottom bar overlaps with text editor space

### ISSUE THREAD

**Issue by Sachin-12** [whyt-byte/Blue-Topaz_Obsidian-css#124]
![image](https://user-images.githubusercontent.com/24960422/143660310-b8c7d55b-5b67-47a5-b06c-7c55ed1d2bfd.png)
Hi. Not sure if this is intended. But it feels quite different to me. I could see at the bottom of the page, things gets overlapped as shown in the screenshot

**Comment by whyt-byte** [comment]
It's a kind of optional appearance for the bottom status bar. You can activate the button in the Style Settings plugin as shown below then to get the original status bar. Have fun!

![image](https://user-images.githubusercontent.com/72023275/143669325-5198c0d9-e917-4b07-bd2e-5db476110a35.png)

**Comment by Sachin-12** [comment]
Thanks! A new plugin. Seems interesting
