### ISSUE TITLE
v0.9.16 frontmatter YAML區域的tags顯示

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#13]
在本文裡的tags的顯示：
![image](https://user-images.githubusercontent.com/131511/99755399-a9f32280-2b25-11eb-9cb0-3813d3fe025b.png)

因為v0.9.16可以在開頭用tags了，這裡的tag能否也可以比較內文的顯示？
![image](https://user-images.githubusercontent.com/131511/99755487-de66de80-2b25-11eb-937b-fca0bd65e8f3.png)

**Comment by whyt-byte** [comment]
谢谢反馈，我还没有使用0.9.16的这个功能，我先看看怎么使用

**Comment by whyt-byte** [comment]
最终大概长这样：
![image](https://user-images.githubusercontent.com/72023275/99816215-5533c400-2b86-11eb-9caa-599f60397815.png)

---
目前有些问题要解决：
![image](https://user-images.githubusercontent.com/72023275/99816225-582eb480-2b86-11eb-9344-d5554fc35c54.png)
