### ISSUE TITLE
支持Code Block Enhancer插件

### ISSUE THREAD

**Issue by Greapi** [whyt-byte/Blue-Topaz_Obsidian-css#131]
和 `Code Block Enhancer` 此款插件类似

![image](https://user-images.githubusercontent.com/51920111/144052363-ffd1c07d-8f53-4ae7-8074-18e5e54ad7a2.png)

**Comment by whyt-byte** [comment]
想问一下，使用插件提供的行号有什么问题吗？

**Comment by Greapi** [comment]
主要是插件的粘贴和皮肤的拷贝按钮重叠了，而插件那边也不能单独取消😂

其实如果可以去掉主题中的拷贝按钮也不失为一种解决方案😁

![image](https://user-images.githubusercontent.com/51920111/144240443-3b827cbe-21a4-4cb1-b173-fd2102c7477d.png)

**Comment by whyt-byte** [comment]
好的，css做成的行号有很大的限制，所以这个需求换做支持插件。

另外一提，codemirror options好像也有行号显示。

**Comment by Greapi** [comment]
的确使用 `codemirror options` 就能互不干扰的显示行号了，谢谢提点👌
