### ISSUE TITLE
RTL alignment text and remove YAML logo

### ISSUE THREAD

**Issue by Alexnoj** [whyt-byte/Blue-Topaz_Obsidian-css#134]
![1](https://user-images.githubusercontent.com/30004592/144705995-0fbe8a6a-d8df-4b1f-82d0-20d0c5d96024.PNG)
![2](https://user-images.githubusercontent.com/30004592/144705997-148f5c45-63ba-455b-880a-97a5efbd92f4.PNG)

Is it possible to fix this RTL issue?
Also, option to remove YAML logo can be helpful.

**Comment by whyt-byte** [comment]
Hi Alexnoj,

You can use the following code to create a CSS snippet for removing "YAML". I am thinking about whether to provide a button to remove it in the Style Settings plugin.

```css
pre.frontmatter.language-yaml::before {
  display: none;
}
```

---

For the second image above, the tangled lines have been fixed. If there are still problems, you can turn off the option in the Outliner plugin, "Improve the style of your lists".

Have fun!

**Comment by Alexnoj** [comment]
> 

Thank you
