### ISSUE TITLE
和Ipad的兼容性不太好/not compatible with ipad os

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#139]
I'm uisng the latest theme fetched from the build-in theme market
The Obsidian Mobile is 1.0.5

1. 标题栏的文字有一半（上半部分）包括菜单按钮都被系统的分屏按钮遮挡住了/the upper half part of the note title as well as the upper part of the menu button are hidden behind the ipad os split screen bar
2. 行号无法显示/the line number does not show up

**Comment by whyt-byte** [comment]
你好，这两个问题都已经修复了，谢谢你报告这些问题，对于这些问题造成的困扰，在此抱歉。

**Comment by zhao414** [comment]
要谢谢您的辛苦努力才是 ：）
