### ISSUE TITLE
frontmatter裡的小問題

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#14]
Hi，兩個小問題，不改也可以，大致不影響外觀：
1. 第二個冒號被變色了
2. 若有啟用Copy button for code blocks plugin時 "Specification" 會被蓋到

![image](https://user-images.githubusercontent.com/131511/99865903-f56e0500-2be7-11eb-9348-6e7cc6c61bc1.png)

**Comment by whyt-byte** [comment]
好的，谢谢反馈。还没改完，没有最终发布。那个插件我没用过，我装上看看

**Comment by whyt-byte** [comment]
冒号那个我无法复现，已经支持copy code插件，目前长这样：
![image](https://user-images.githubusercontent.com/72023275/99901729-d9578a00-2cf3-11eb-98d0-fb291fa4cc74.png)

还没有全部改好，可以等v1.3发布后更新
