### ISSUE TITLE
反向链接样式

### ISSUE THREAD

**Issue by iris2jane** [whyt-byte/Blue-Topaz_Obsidian-css#15]
您好，发现[这个主题](https://github.com/GuangluWu/obsidian-pisum)的反向链接样式似乎更加清晰明了，希望能有参考价值
<img width="313" alt="image" src="https://user-images.githubusercontent.com/36763930/99881894-892aea00-2c57-11eb-948d-58fe13ee9b34.png">

**Comment by whyt-byte** [comment]
你的意思是"加个背景色"，是吗？

**Comment by iris2jane** [comment]
是的，像这样多文件或者同一文件多处被引用提及，加个背景看起来比较“一体化”。
而且文件标题也许不用彩色，可以让界面更简洁些，利于阅读。
<img width="324" alt="image" src="https://user-images.githubusercontent.com/36763930/99883772-7ff44a00-2c64-11eb-9483-0cb26b057a41.png">
