### ISSUE TITLE
Colorful Folders Truncates Folder Depth

### ISSUE THREAD

**Issue by MalignantCarp** [whyt-byte/Blue-Topaz_Obsidian-css#152]
I really love the colorful folders, but they wreak havoc on folder depth and make it hard to tell when something is inside another folder once you've reached a certain depth. See the highlighted (Series Ov) entry in the two screenshots:

![image](https://user-images.githubusercontent.com/93364935/145730716-1262118f-12d4-4c6e-aec5-91f0adfef7ad.png)

vs

![image](https://user-images.githubusercontent.com/93364935/145730730-903dc7f0-3228-41f5-bc12-f824f6ad91f1.png)

Is this expected behaviour?

**Comment by whyt-byte** [comment]
I am sorry that I didn't notice this. Now it's fixed. Thank you for your report.
