### ISSUE TITLE
Colorful folders - inner most folder misaligned and missing border-left under arrow

### ISSUE THREAD

**Issue by MalignantCarp** [whyt-byte/Blue-Topaz_Obsidian-css#155]
I had a hard time describing this one in the title 😅. With colorful folders enabled, innermost folder children are at the same alignment as the parent folder's regular file children and the line that normally appears under the arrow is missing:

![image](https://user-images.githubusercontent.com/93364935/146275820-7083a23b-91c7-4881-ae4e-e430c6ab237e.png)

![image](https://user-images.githubusercontent.com/93364935/146275604-52134773-5c61-453d-b0b7-44911396209a.png)

vs
![image](https://user-images.githubusercontent.com/93364935/146275857-a2008f3f-a3b3-46f5-97f4-02349af224d5.png)

![image](https://user-images.githubusercontent.com/93364935/146275695-dd16207c-035b-42a4-bb3e-3dfcd5b0b020.png)

**Comment by whyt-byte** [comment]
Yep, it's quite hard to specify just using a verbal description. The screenshots are helpful indeed.😄

I have fixed it and will turn to your next issue.
