### ISSUE TITLE
[Feature request] Add relationship line in edit mode

### ISSUE THREAD

**Issue by vizance** [whyt-byte/Blue-Topaz_Obsidian-css#158]
Hello,

REALLY LOVE this fantastic theme ! 

Is it possible to add list relationship line shown in edit mode as preview mode ? see below picture for reference. 

Big thanks !

<img width="1068" alt="CleanShot 2021-12-17 at 12 36 33@2x" src="https://user-images.githubusercontent.com/29624657/146489665-97f7553a-3e88-4379-81e5-39f90eefa2be.png">

**Comment by sbusso** [comment]
i'd love to see that too!

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/148679852-0978b067-756a-438e-b8cf-96bf65a12539.png)
with style settings plugins  2.3.9

**Comment by vizance** [comment]
@cumany  thanks so much !

**Comment by whyt-byte** [comment]
Thank you for liking the theme! The list now has grey vertical lines by default in Live Preview mode, and of course, you can choose the "Rainbow Outline" to continue using the rainbow style above.
