### ISSUE TITLE
frontmatter v0.9.17的修改

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#16]
v0.9.17 frontmatter裡的tags可以不加井號了，反而會影響到新的設定，如下圖 obsidian 標籤沒有被套用到新的樣式：

![image](https://user-images.githubusercontent.com/131511/99905146-e97a6400-2d09-11eb-9281-925f857ffbd3.png)

**Comment by whyt-byte** [comment]
格式是更改引号”“里的内容，我再看看怎么改吧。后面比较忙，会停更一段时间，先抱歉了

**Comment by emisjerry** [comment]
v0.9.18增加了METADATA區域，或許這個顯示不用修改了？

![image](https://user-images.githubusercontent.com/131511/100297924-bdd9d100-2fca-11eb-8a57-e42c079ae72a.png)

**Comment by whyt-byte** [comment]
好的，谢谢告知。
