### ISSUE TITLE
样式设置在 Live Preview 模式中不起作用

### ISSUE THREAD

**Issue by raawaa** [whyt-byte/Blue-Topaz_Obsidian-css#161]
Live Preview 已经正式发布了，发现很多样式在 Live Preview 中不生效，目前发现的包括：
 - 列表样式
 - 彩虹大纲线
 - 字间距
 - 主体字体

**Comment by zhl111** [comment]
还有图片注释img-captions也不起作用了

**Comment by laolai** [comment]
其他还好，正文不生效，导致正文跟标题字体不一致，看起来好怪啊😂
![image](https://user-images.githubusercontent.com/3068867/147184702-5c630aae-ec5a-4e23-ba9b-4cfdfc49d84a.png)

**Comment by cumany** [comment]
![标题显示级别](https://user-images.githubusercontent.com/42957010/147333328-7f8bc101-3f91-4ab5-a0c6-8e7a329f437e.gif)
最新版主题彩虹线已经修复正常

**Comment by cumany** [comment]
主题使用教程和示例库 可以参考这个 [](https://kknwfe6755.feishu.cn/docs/doccn67RYLVN4IQZiJTwviIdnog#)

**Comment by whyt-byte** [comment]
基本处理完了
