### ISSUE TITLE
Readable line length option doesn't work after last updates in Live Preview mode

### ISSUE THREAD

**Issue by halega** [whyt-byte/Blue-Topaz_Obsidian-css#164]
1. Turn off Editor -> Readable line length
2. Maximaze Obsidian window

**Expected result**
Line should fill all available width.

**Actual Result**
![image](https://user-images.githubusercontent.com/35935/147381145-5c85bed8-7fcf-4d60-ae24-000c3d7ec0ad.png)

as if I have Readable line length option turned on.

**Comments**
And now if you change window widths the cursor behave strangely (it placed outside edit field):

![image](https://user-images.githubusercontent.com/35935/147381188-55574dda-0e6a-43ca-8179-605531d84ece.png)

Obsidian v.0.13.14
Windows 11

**Comment by whyt-byte** [comment]
I have fixed the first bug you mentioned. Thank you for your report. BTW, you can adjust the width of "readable mode" in the Style Settings plugin.

The second one is caused by the software, not by the theme. So we have to wait for the developers to fix the bug.
