### ISSUE TITLE
Arabic characters

### ISSUE THREAD

**Issue by karimhsa** [whyt-byte/Blue-Topaz_Obsidian-css#167]
It would be possible that the size of the text writen in Arabic characters was shown according to the text in Latin characters?
Currently it is very difficult to read the text written in Arabic mixed with the text written in Latin. I think the solution could be to increase the size of the Arabic text by 100%. Now to be able to read arabic text we must set font size from 16 to nearly 26...

Thanks for your attention.

**Comment by whyt-byte** [comment]
Unfortunately, CSS cannot select the type of language within a paragraph, so it cannot achieve what you want.

A possible solution is to change to another Arabic font family with a larger font size under normal font style.
