### ISSUE TITLE
在(传统)编辑模式下, 引用`>`中, 使用多行公式, 会出现渲染问题

### ISSUE THREAD

**Issue by AntoineChn** [whyt-byte/Blue-Topaz_Obsidian-css#168]
作者您好, 感谢您的主题, 它十分美观实用. 

在今天的使用中, 我遇到如下问题, 如下代码 在编辑页面 (这里指传统编辑界面, 而非WYSIWYG) 有渲染问题, 但是 预览界面正常

```markdown
> $$
> \left\{ \quad
> \begin{aligned}
>     g\left( x \right) & \leqslant 0 \\
>     0 &  \leqslant f\left( x \right)
> \end{aligned}
> \right.
> $$
```

如图

![Screenshot 2021-12-26 at 21 10 13](https://user-images.githubusercontent.com/17791254/147418973-1a740e55-2cd9-4f8f-b409-b99893440449.png)

请问这个问题 是否方便解决呢? 

提前感谢

**Comment by cumany** [comment]
这个貌似不是主题问题吧 在所见即所得版本中默认主题也是这样

**Comment by AntoineChn** [comment]
@cumany 谢谢你的回复. 

我忘记说明了, 我没有使用所见即所得. 而是使用传统的编辑界面. 
这个主题, 在传统编辑界面也有很漂亮的渲染 (像我上面的截图那样). 

我记得之前, 在编辑界面渲染的 是没有渲染问题的. (也可能是我记错了)
