### ISSUE TITLE
變更圖片的Pixels失效

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#17]
變更圖片的Pixels失效，預設主題是正常的。下例 |100 指定要用100Pixels，但無變化。

```
![Engelbart|100](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg)
```

預設樣式：
![image](https://user-images.githubusercontent.com/131511/100056054-f0b38600-2e5f-11eb-9404-d294b57edb43.png)

Blue Topaz:
![image](https://user-images.githubusercontent.com/131511/100056117-0e80eb00-2e60-11eb-98ed-e768c2946264.png)

**Comment by whyt-byte** [comment]
收到，谢谢，已记录
