### ISSUE TITLE
修改edit状态的字体

### ISSUE THREAD

**Issue by rangluwme** [whyt-byte/Blue-Topaz_Obsidian-css#173]
![image](https://user-images.githubusercontent.com/63960943/147468775-fa3c9923-37f5-4293-a022-cd79917e1712.png)
您好，我想修改编辑状态的字体，我使用了style setting插件，但是还是没有任何效果，在主题css中，我把所有的字体设置为微软雅黑，但是还是没有效果，请问该如何修改，谢谢。

**Comment by whyt-byte** [comment]
检查以下事项：
1. 确认系统是否安装改字体
2. 字体名称输入是否正确
