### ISSUE TITLE
关于首行缩进出现的问题

### ISSUE THREAD

**Issue by RuJingTingShan** [whyt-byte/Blue-Topaz_Obsidian-css#174]
如果原来的文本已经首行缩进了，再用这个功能就会变成4个字的空白
![截图26](https://user-images.githubusercontent.com/96676995/147525438-22def99a-bfae-4f07-9487-a2a1c58d5183.jpg)

--------
![截图21](https://user-images.githubusercontent.com/96676995/147525209-019c3072-c18c-4265-b2da-f20918cd536e.jpg)
普普通通1个回车的换行，被识别为同一个段落，只有第一个才缩进

**Comment by whyt-byte** [comment]
我不太明白，如果已经有别的首行缩进方式，为什么还要开这个功能呢？

**Comment by RuJingTingShan** [comment]
> 我不太明白，如果已经有别的首行缩进方式，为什么还要开这个功能呢？

因为那不是“别的首行缩进”方式，而是有的文章排版时自带两个空格。
但这种文章比较少。
本意是想能否增加一个if判断，后来想想算了，又不是什么大问题，加了判断反而影响运行效率。

问题2，经过这段时间的摸索弄明白了，obs是以2个回车来判断一个“block”的，只有block才会加上首行缩进。

**Comment by whyt-byte** [comment]
很可惜，css并不是一种编程语言，没有办法进行条件判断，首行缩进是对p标签设置的，暂时没有什么好的优化方式
