### ISSUE TITLE
Live Preview模式下标题的下划线样式不生效

### ISSUE THREAD

**Issue by fuckgfwfuckfuck** [whyt-byte/Blue-Topaz_Obsidian-css#178]
如图
![image](https://user-images.githubusercontent.com/81576130/147844534-f753f197-8028-4eaf-8cda-71cf7a67b309.png)

需要切换至阅读模式，才能看到标题的下划线
![image](https://user-images.githubusercontent.com/81576130/147844549-01f5c7ab-2f2c-437d-bdbe-7e9fecbd3003.png)

**Comment by whyt-byte** [comment]
没有不生效，因为没有设置编辑模式的标题下划线，暂时也没有准备进行下划线设置
