### ISSUE TITLE
中英文字间距能设置吗

### ISSUE THREAD

**Issue by lijyze** [whyt-byte/Blue-Topaz_Obsidian-css#183]
中英文之间可以自动加间距吗，除了手动加空格外有什么比较体面一点的方法吗？
<img width="644" alt="image" src="https://user-images.githubusercontent.com/26381964/148503062-13fc44b8-55f9-4f49-aa8e-3c518ac093b5.png">

**Comment by whyt-byte** [comment]
css不能识别中英文，所以无法做到。你可以在style settings里更改字间距选项，看看能不能达到你的要求。

**Comment by lijyze** [comment]
> css不能识别中英文，所以无法做到。你可以在style settings里更改字间距选项，看看能不能达到你的要求。

谢谢大佬回复，那行内代码段的左右外边距能设置吗

**Comment by northword** [comment]
> 除了手动加空格外有什么比较体面一点的方法吗？

[盘古插件](https://github.com/Natumsol/obsidian-pangu)
