### ISSUE TITLE
tags in data view seem off? (bug?)

### ISSUE THREAD

**Issue by zeltak** [whyt-byte/Blue-Topaz_Obsidian-css#184]
Hi!

the Dataview tags seem really unreadable 

![image](https://user-images.githubusercontent.com/498410/148524787-a53be320-a0a1-4cd8-8828-f0ae330d7cc5.png)

any way to fix this?

other themes seem to handle this in a much cleaner way:

![image](https://user-images.githubusercontent.com/498410/148524962-e8c31440-600e-429b-95e1-7f30541093f4.png)

thx

Z

**Comment by whyt-byte** [comment]
I think it has been fixed. Please have a check.

**Comment by zeltak** [comment]
perfect! thx so much
