### ISSUE TITLE
如何去掉截屏图片

### ISSUE THREAD

**Issue by Nicolas-XF** [whyt-byte/Blue-Topaz_Obsidian-css#188]
在三星手机上长截屏的时候只下去一屏就停了，换其它主题可以完整长截屏，怀疑是背景引起的，可以手动去掉吗？这主题太好了

**Comment by whyt-byte** [comment]
可以使用style settings插件去除背景。可以去除背景后再截屏试试，然后麻烦给个反馈，方便我进行优化

**Comment by Nicolas-XF** [comment]
![image](https://user-images.githubusercontent.com/21361330/148943612-0e38f352-9344-4587-8374-4396c2340ac1.png)

感谢如此快的回复，的确是背景的问题，去掉后手机长截屏没有问题了

**Comment by whyt-byte** [comment]
非三星手机，无法复现，可以正常截屏。
