### ISSUE TITLE
代码块阅读模式下第一行对不齐

### ISSUE THREAD

**Issue by conscloud** [whyt-byte/Blue-Topaz_Obsidian-css#189]
代码块在编辑页面时行与行之间是对齐的，如下：
![image](https://user-images.githubusercontent.com/18484709/149488652-586e69b0-f973-4504-8e26-26e77ed6447a.png)
切换到阅读模式下后，第一行与后面的行之间对不齐，如下：
![image](https://user-images.githubusercontent.com/18484709/149488761-f42a88ee-5a3e-4346-bd73-09174d3af2c8.png)

如果有声明了语言则就没有问题：
![image](https://user-images.githubusercontent.com/18484709/149489068-17e76458-3606-42a0-9bc6-b3580e74ab70.png)
``
![image](https://user-images.githubusercontent.com/18484709/149489099-7ba8242f-edd0-4fc2-834d-7f8b6e9a6eef.png)

换自带主题就没有这种情况。

**Comment by whyt-byte** [comment]
谢谢报告，已修复
