### ISSUE TITLE
样式细节问题

### ISSUE THREAD

**Issue by iris2jane** [whyt-byte/Blue-Topaz_Obsidian-css#19]
1. css 中的间距能否都尽可能缩小
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/36763930/100305594-57f64500-2fdc-11eb-8003-d86fd70c39ab.png">

2. 反向链接样式不统一
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/36763930/100305814-e1a61280-2fdc-11eb-9fba-a829ae854222.png">

**Comment by whyt-byte** [comment]
反链样式是统一的，右边背景是灰的而已
