### ISSUE TITLE
feature request: Readable line length on iPad

### ISSUE THREAD

**Issue by albfaggion** [whyt-byte/Blue-Topaz_Obsidian-css#191]
My request is a way to have readable line length on the iPad.

**Comment by whyt-byte** [comment]
Hi albfaggion,

Please first update the theme, then you could adjust the line width by using the Style Settings plugin, as shown below.
Have fun!
![image](https://user-images.githubusercontent.com/72023275/150643450-22d82d46-18c8-4e6a-a63a-fe3403551eb1.png)
