### ISSUE TITLE
如何复制主题样式

### ISSUE THREAD

**Issue by A2Data** [whyt-byte/Blue-Topaz_Obsidian-css#192]
因为有写公众号的需求，但是复制粘贴过去之后，会粘贴原文。 想再预览页增加 复制全文的按钮。
可以把css样式也复制上。 希望可以支持下。

或者有类似插件推荐吗 
新人入坑 obsidian

**Comment by whyt-byte** [comment]
都是css做不到的事，我也没听说过类似插件
