### ISSUE TITLE
在新的Live Preview模式下和Outliner插件存在适配问题

### ISSUE THREAD

**Issue by williamlorder** [whyt-byte/Blue-Topaz_Obsidian-css#193]
你好，感谢你开发了这么优秀的主题。然而我发现主题在新版的outliner插件下，大纲的竖线消失了。我记得在旧版时当使用Outliner时会出现竖线的。你可以看下面的图。
<img width="743" alt="截屏2022-01-20 23 10 35" src="https://user-images.githubusercontent.com/83387569/150365928-3822e55f-813f-4131-bc64-63b5443b4e60.png">

原版主题下竖线可以显示的，请看下面的图
<img width="743" alt="截屏2022-01-20 23 11 38" src="https://user-images.githubusercontent.com/83387569/150366122-2729e590-768c-4386-948e-60cd72d83009.png">

**Comment by zhao414** [comment]
装个 style setting 插件
然后打开 Bluetopaz 的配置页面
进入里面配置项 2.3.9 rainbow outline
按需把三种 outline 格式的开关打开，就可以了。

**Comment by williamlorder** [comment]
事情完美解决了！！！感谢，还有一个小问题就是我发现在新版的可视化编辑下。大纲的点会显得特别小。你可以看下面这张图。是否有办法把点的尺寸给调大。
<img width="526" alt="截屏2022-01-22 00 06 03" src="https://user-images.githubusercontent.com/83387569/150560417-056a6e69-accb-44f4-86d2-bb68ace1e47a.png">

**Comment by whyt-byte** [comment]
请更新主题，层级线以及彩虹层级线这些设置做了一些调整，现在live preview默认存在灰色的层级线，bullet point也做了相应调整，与预览模式一致。

**Comment by zhao414** [comment]
> 请更新主题，层级线以及彩虹层级线这些设置做了一些调整，现在live preview默认存在灰色的层级线，bullet point也做了相应调整，与预览模式一致。

目前，层级线只有灰色了。bullet point 倒是彩色的。
