### ISSUE TITLE
似乎彩虹大纲先并不生效

### ISSUE THREAD

**Issue by williamlorder** [whyt-byte/Blue-Topaz_Obsidian-css#195]
新版更新后，采用彩虹大纲样式似乎并不生效。如下图
<img width="893" alt="截屏2022-01-24 01 43 48" src="https://user-images.githubusercontent.com/83387569/150690957-b102516d-481c-4717-84d1-40d9134fdc67.png">
另外对于outliner的适配也不太好。会出现两个点重叠在一起。
<img width="766" alt="截屏2022-01-24 01 45 41" src="https://user-images.githubusercontent.com/83387569/150691051-36c35c84-6089-4e2f-844c-4fa0dc7ccc57.png">

**Comment by zhao414** [comment]
observation：垂直线条只有灰色了。
Bullet Point：没发现类似问题。

**Comment by cumany** [comment]
更新主题再看看

**Comment by zhao414** [comment]
It works now!
