### ISSUE TITLE
can one select/define custom colors for the folder style background?

### ISSUE THREAD

**Issue by zeltak** [whyt-byte/Blue-Topaz_Obsidian-css#205]
Hi, keep loving to death this theme!! thx so much for working on it

I was wondering if one could select/define custom colors for the folder style background? the built in 5 styles done fit my taste :) or maybe i can shift assign these colors to the letter i want (currently it auto assigns colors based on `ABC`, right?)

![image](https://user-images.githubusercontent.com/498410/151787041-915140d6-f340-49a4-b7d2-367985678ddf.png)

thx so much

Z

**Comment by cumany** [comment]
The latest theme already supports custom folder color
