### ISSUE TITLE
Dataview 表格問題

### ISSUE THREAD

**Issue by chuhenry** [whyt-byte/Blue-Topaz_Obsidian-css#209]
開發者您好,

在使用這款插件時，發現 Dataview query 有 2 個可優化的地方。

## 1. Live Preview 下的 Editing Mode，可增加表格背景顏色更好閱讀

以下是用 `Dataviewjs` query 出的表格，可發現表格的列之間沒有背景顏色，比較難閱讀
![CleanShot 2022-02-11 at 16 25 09@2x](https://user-images.githubusercontent.com/95008347/153558970-f59d6db9-93a6-4d67-969a-d70a674a6317.png)

對照 `Reading view`，會好閱讀許多
![CleanShot 2022-02-11 at 16 26 31@2x](https://user-images.githubusercontent.com/95008347/153559109-27b5bfbf-3df5-433a-8877-13a3b3e056d0.png)

## 2. Dataviewjs query 會讓表格延伸，我希望表格行為是讓文字換行 (wrap)
下面的 GIF 演示在 `Reading view` 下，表格會變成需要左右拖移，但是在 `Editing view` 文字換行的
![CleanShot 2022-02-11 at 16 27 43](https://user-images.githubusercontent.com/95008347/153559323-979dc93b-362a-40cc-8e5b-a1626c97ec43.gif)

如果換成 `Minimal Theme`，表格會是文字換行，不過閱讀性沒有  Blue Topaz 來得好
![CleanShot 2022-02-11 at 16 31 29@2x](https://user-images.githubusercontent.com/95008347/153559883-5e407d5c-81a8-4348-a5a2-3faacdc4da27.png)

謝謝您辛苦的付出，真的很喜歡這個主題！

**Comment by cumany** [comment]
关于第一个问题 更新主题 下个版本解决。
关于第二个问题，style setting 插件3.6.1 设置中，Dataview 表格紧凑显示关闭，就可以让表格内文字换行显示。

**Comment by chuhenry** [comment]
@cumany 了解了！謝謝回覆
