### ISSUE TITLE
Note Embeds don't show any headings

### ISSUE THREAD

**Issue by TheDenast** [whyt-byte/Blue-Topaz_Obsidian-css#212]
When embedding a note (for example **![[Principle of Superposition#Linearity]]** ), the embedded note skips all headings it has in the preview mode. 
**Original note:**
![error2](https://user-images.githubusercontent.com/99830990/154329191-43559792-0684-49e4-9be9-1f4b6ef5bcb6.png)
**Same note embedded:**
![error1](https://user-images.githubusercontent.com/99830990/154329271-78b6ac0f-b743-432e-a132-b6c3d6e279dc.png)

**Comment by cumany** [comment]
please 
turn off “2.3.6 embed==》hide embed headings“   with style settings plugin
