### ISSUE TITLE
Bug: Video Maximize 

### ISSUE THREAD

**Issue by faysalforbd** [whyt-byte/Blue-Topaz_Obsidian-css#215]
https://user-images.githubusercontent.com/22533345/154515189-854fb3f4-a430-442e-9d9e-b5dc6b30d6b2.mp4

At first I was thinking it was a media extend plugin issue, but then I tried with a completely new vault. I'm not familiar with any problems. This problem occurs when I enable the Blue Tropez theme.

**Comment by cumany** [comment]
Update the theme, it has been fixed
Have fun!

**Comment by faysalforbd** [comment]
Thank You So much 😍
