### ISSUE TITLE
通过插件自定义设置

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#22]
希望可能通过obsidian的插件对字号和字体进行自定义，如果能支持颜色就更好了

**Comment by whyt-byte** [comment]
不会js。css内可修改

**Comment by whyt-byte** [comment]
css开头已设置字体、字体大小的修改处，obsidian 0.9.18版本后可以设置css snippets，可以将修改后的字体、字体大小代码放在snippet文件夹内，会覆盖css内的相关内容，不用每次css更新再更改
