### ISSUE TITLE
右侧进度条太细了，点不到。

### ISSUE THREAD

**Issue by ssmmtt** [whyt-byte/Blue-Topaz_Obsidian-css#220]
![image](https://user-images.githubusercontent.com/16244320/155475125-4c7f839f-d4e8-44f4-9bb7-645040f260cb.png)
这个进度条太细了，很容易触发调整窗口大小的操作，能不能鼠标到这自动变宽？

**Comment by cumany** [comment]
更新主题 已经修复了
