### ISSUE TITLE
Feature Request: Support for cards

### ISSUE THREAD

**Issue by ganesshkumar** [whyt-byte/Blue-Topaz_Obsidian-css#221]
Is it possible to add support for cards similar to Minimal theme via these [helper classes](https://github.com/kepano/obsidian-minimal#helper-filters-and-classes)?

**Comment by cumany** [comment]
Of course, this feature has been supported for some time, so please keep us updated!
![image](https://user-images.githubusercontent.com/42957010/155669665-944346bf-09cb-4a11-a1fa-054acb25d085.png)
![image](https://user-images.githubusercontent.com/42957010/155669743-92cfcb9d-f335-47a7-af6d-4244c78d3a67.png)

**Comment by cumany** [comment]
| cssclass    | role                                                               |
| ----------- | ------------------------------------------------------------------ |
| code-wrap   | code-block-auto-wrap                                               |
| img-grid    | image adaptive distribution                                        |
| inline-list | images and lists mixed                                             |
| kanban      | pseudo-kanban style, unordered list of four columns                |
| fullwidth   | reduce column width on, control the full width of the page display |
| noscroll    | hide the current page scrollbar                                    |
| matrix      | four-quadrant table style                                          |
| cards       | rendering-dataview-tables-to-cards-view                            |
| cards       | rendering-dataview-tables-to-cards-view                            |
| noyaml      | preview state does not show the frontmatter area                   |
