### ISSUE TITLE
这个是否也设置成可选项，依个人需要在Style Settings里选择？

### ISSUE THREAD

**Issue by chenxin0397** [whyt-byte/Blue-Topaz_Obsidian-css#223]
左边的文档列表能不能还原成默人的不换行状态？否则一但左边太窄，文件名列表就一行变两行，本就不高的屏幕被挤的满满的。
![QQ五笔截图未命名](https://user-images.githubusercontent.com/73974352/155737781-a6e78ce0-da40-4879-9e49-04379dbbde46.png)
而且鼠标停留就能看到从浮窗里看到的文件名被取消了感觉功能反而受限，
![QQ五笔截图未命](https://user-images.githubusercontent.com/73974352/155737807-446fe6ef-bd7b-4f69-93d1-3deb96c4b449.png)
不知是否也设置成可选项，依个人需要在Style Settings里选择？

![2 (1)](https://user-images.githubusercontent.com/73974352/155737912-7c9a740a-02cc-47c7-afc1-8589f25bd619.gif)
一 直想到这个效果是怎么实现的，这个文件名是26个英文字母。虽然没有结果，但从图中也看出用的是Blue Topaz这个主题，当时浮动框还能显示文件名。

**Comment by whyt-byte** [comment]
#210 
请不要重复提issue
