### ISSUE TITLE
在Style Setting开啟2.2.3显示标题阶层后，用中文输入法输入数字或符号时会自动进入取代模式

### ISSUE THREAD

**Issue by web8823** [whyt-byte/Blue-Topaz_Obsidian-css#224]
- 主题已更新为最新版本 (6.0)
- 我在使用中文输入法并切换成了打中文的模式
- 我在用Live Preview

在Style Setting开启2.2.3底下的Clutter Free Headings后，标题(heading)有成功显示出，但是打出来的数字或符号会自动被选取（应该类似键盘上的 Insert 按键）而非直接输入出来，有时候第一个数字或符号是可以成功打出，但接着打就还会是这样。

我测到如果在有标题的情况下打出bullet list之类而不单单是普通文字的话，就会出现这种情况（如图）；也就是如果整个页面只有标题和普通文字，没有bullet list之类的，数字和符号是可以成功打出的。

![image](https://user-images.githubusercontent.com/93432430/155770246-6339ca17-cdba-4d7c-83a6-c7744363adaf.png)

**Comment by web8823** [comment]
同時如果有開啟多個頁面的話，在這自動選取的期間再按一次就會直接跳到旁邊的頁面上輸入

**Comment by cumany** [comment]
貌似最新的 ob 0.13.30 版本修复了这个问题

**Comment by web8823** [comment]
> 貌似最新的 ob 0.13.30 版本修复了这个问题

感謝告知，目前用起來沒什麼問題
