### ISSUE TITLE
[不紧急] 多行脚标, 在编辑模式下, 存在 1)字体大小不同 & 2) 缩进不同 的问题

### ISSUE THREAD

**Issue by AntoineChn** [whyt-byte/Blue-Topaz_Obsidian-css#225]
## 问题描述

如题所言, 当 footnotes 存在多行时, 在编辑模式下, 这几行文字 存在 1)字体大小不同 & 2) 缩进不同 的问题

特别说明, 预览界面无此问题, 所以这个问题并不急迫

## 截图

![Screenshot 2022-03-02 at 23 45 34](https://user-images.githubusercontent.com/17791254/156462524-1f95effc-b158-414b-a807-3f6b0e884356.png)

## 用于复现的 代码

```markdown
至主题维护者们[^1]

[^1]: 辛苦啦
	加油加油
```

**Comment by whyt-byte** [comment]
非主题问题，在现有版本下无法优化
