### ISSUE TITLE
Bullet icon disappeared in the Live Preview mode

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#227]
with default theme
![image](https://user-images.githubusercontent.com/15528506/157177895-24f27497-a9ed-461a-8ef8-dfb6a24250bd.png)

with blue topaz theme
![截屏2022-03-08 14 10 52](https://user-images.githubusercontent.com/15528506/157177766-1af1afb3-da77-4849-a1fe-4d30939a7359.png)

**Comment by cumany** [comment]
#230  fixed
