### ISSUE TITLE
"style setting"修改后重启失效

### ISSUE THREAD

**Issue by yanwanchen720** [whyt-byte/Blue-Topaz_Obsidian-css#229]
好像跟版本有关，有一个版本更新前修改重启后是继承的。
更新后通过“style setting”修改重启后失效。

**Comment by whyt-byte** [comment]
请提供更多信息。通过上面这种描述，我们很难了解你的问题

**Comment by yanwanchen720** [comment]
> 请提供更多信息。通过上面这种描述，我们很难了解你的问题
我的意思是：使用“style setting”插件修改主题后，重新加载obsidian应用，通过“style setting”插件 设置的主题会失效；
这可能和版本某个插件或obsidian的版本有关；

**Comment by yanwanchen720** [comment]
我的意思是：使用“style setting”插件修改主题后，重新加载obsidian应用，通过“style setting”插件 设置的主题会失效；
这可能和某个插件或obsidian的版本有关；



| |
Shuojie
|
|
***@***.***
|
在2022年3月8日 ***@***.***> 写道：

Reopened #229.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whyt-byte** [comment]
有人遇到相似情况，可能是因为软件安装版本过低导致的。请使用最新版安装包重新安装软件

**Comment by yanwanchen720** [comment]
> 有人遇到相似情况，可能是因为软件安装版本过低导致的。请使用最新版安装包重新安装软件

👌👌
