### ISSUE TITLE
代码块有白色的阴影

### ISSUE THREAD

**Issue by shamy1997** [whyt-byte/Blue-Topaz_Obsidian-css#23]
非常感谢你提供的这个精美的主题，但是在使用的时候发现代码块的背景是白色的，比较影响阅读观感，不知道要在哪里修改呢？举例如下：
Thanks for your awesome theme! But the white background of code really bothers me when use this theme to preview. I wonder whether you could tell me where to fix this problem. Example as shown below.Thanks!
![image](https://user-images.githubusercontent.com/20695820/102050073-10194f80-3e1d-11eb-958a-f5c257628877.png)

**Comment by whyt-byte** [comment]
我在最新版的css中没有发现上述问题，而且这个代码框也不是现在使用的风格。麻烦检查一下css的版本代码，在css开头处注释中，形如：[20201209]，如果低于此版本，请尝试更新主题，可在软件内社区主题点击“使用”，自动覆盖更新，或release界面下载更新。

这是现在的外观：
![image](https://user-images.githubusercontent.com/72023275/102192354-a15bf500-3ef5-11eb-9539-3a6d714bb950.png)
