### ISSUE TITLE
6.0版本列表显示异常

### ISSUE THREAD

**Issue by wql201** [whyt-byte/Blue-Topaz_Obsidian-css#231]
使用的是旧版编辑器，在编辑模式下，6.0之后列表显示异常

- 6.0之前

![image](https://user-images.githubusercontent.com/36467877/157210078-607a3d0b-5a29-4778-b325-a777bcdb9c9e.png)

- 6.0之后

![image](https://user-images.githubusercontent.com/36467877/157210579-c4f64c59-a821-47c9-979b-bf83e9d054c5.png)

**Comment by whyt-byte** [comment]
先更新主题
#227

**Comment by wql201** [comment]
css已更新至 20220309，但还是没有效果。

Obsidian：v0.13.30，旧版编辑器
Outliner插件：v1.4.1

**Comment by cumany** [comment]
最新主题下 没发现有此问题出现

**Comment by whyt-byte** [comment]
已修复
