### ISSUE TITLE
a thin vertical line appears on bullet point of the 2nd level list item of a hierarchical list

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#234]
To summary:
- under some conditions, there is a very thin vertical line appearing on the bullet point of the 2nd level of a hierarchical list when the rainbow outline is applied.
 
先上图：
注意二级 list 的 bullet point，这个问题只出现在第二级list 中。
正常(Normal)
<img width="1251" alt="截屏2022-03-08 21 50 09" src="https://user-images.githubusercontent.com/15528506/157251311-5b88680e-3747-4f74-aa15-52bcc76891a9.png">

异常（第二级且仅第二级的bullet point 上出现了一条细线）(Abnormal, vertical thin line appears on bullet point of 2nd level)
<img width="1251" alt="截屏2022-03-08 21 50 16" src="https://user-images.githubusercontent.com/15528506/157251271-47352684-97fa-4a9f-b992-fe67bf8b9402.png">

复现方法：##To reporduce
1. Obsidian 字体调整到18 号 ##set the obsidian font size to 18 
2. 创建一个笔记，打开 Live Preview ## create a new note as the following with the live preview turned on

```markdown
- list1 ^c9b22a
	- list2
	- list2-1
	- list2-2 ^c9b22b
		- list3
		- list3-1
		- list3-2 ^c9b22c
			- list4 ^c9b22d
				- list5 abcdefghigklmnopqrstuvwxyz ^c9b22e
					- list6 ^c9b22f
						- list7
```
3. 用鼠标调整当前打开的这个笔记panel的宽度，并观察第二级 bullet 的 bullet point ## adjust the width of the note panel, and observe the bullet point of the 2nd level list item.
3.1 在一些宽度下，第二级 bullet point 上会出现一条竖线。## Notice that with some width, a thin vertical line appears.
3.2 在一些宽度下，第二级 bullet point 又恢复正常 ## Notice that with some other width, the aforesaid thin vertical line disappears.

**Comment by zhao414** [comment]
![Mar-08-2022 22-00-38](https://user-images.githubusercontent.com/15528506/157252782-eeac7e5a-8035-45de-8ab2-2bfb6f324c3b.gif)

**Comment by cumany** [comment]
在0.13.31版本上 我没有复现出来

**Comment by zhao414** [comment]
@cumany 哦，我忘了一个步骤。
- 先通过菜单 view -> actual size
- 再 zoom-in twice
