### ISSUE TITLE
如何修改正文和行内代码的字体

### ISSUE THREAD

**Issue by Azureki** [whyt-byte/Blue-Topaz_Obsidian-css#235]
我想使用 FiraCode 的连体。在正文、行内代码、代码块的字体设置里都添加 `Fire Code`。
![image](https://user-images.githubusercontent.com/22387028/157254961-66332d54-7f80-4983-810b-46847064f1ec.png)
![image](https://user-images.githubusercontent.com/22387028/157254999-d76926aa-2917-4b7a-ac84-24a94f216531.png)

结果：
如图，编辑模式下只有代码块生效。
![image](https://user-images.githubusercontent.com/22387028/157255111-8c0e9bf7-008f-40c8-9215-2fd58e1af96c.png)
而阅读模式下三个地方全都不生效。
![image](https://user-images.githubusercontent.com/22387028/157255320-5cb65765-1287-4fa7-8b06-b3b72a230fff.png)

请问这里的设置为何不生效……第一天折腾 Obsidian，还请您指教。

**Comment by whyt-byte** [comment]
![image](https://user-images.githubusercontent.com/72023275/158007068-67c4840f-24fb-423c-95cd-ec491dac286d.png)
![image](https://user-images.githubusercontent.com/72023275/158007080-cf0910b6-a4ea-45c0-97dc-b621a7dd5127.png)
![image](https://user-images.githubusercontent.com/72023275/158007081-d8852a34-595a-4740-bb20-2384cf707e07.png)

谈不上指教。

设置完字体后，还需要把字间距调到0（增加字间距这种设置是为了让中文阅读更舒服一些）
![image](https://user-images.githubusercontent.com/72023275/158007129-9acd0276-df6b-44f2-9293-7968305dfa28.png)
