### ISSUE TITLE
display of the hamburger to get the file explorer to show isn't there

### ISSUE THREAD

**Issue by pcause** [whyt-byte/Blue-Topaz_Obsidian-css#236]
I am on mobile and dark mode.  In other themes there is a hamburger item in the top left that I can tap to get the left pan to show which is usually the file explorer.  This isn't present in thiss theme which is my default for desktop.  I prefer to use on mobile but cant without this

**Comment by cumany** [comment]
You can try to slide the screen to the right, of course I prefer to sliding the title bar

**Comment by pcause** [comment]
no, swiping right is the back gesture and so it can go back a screen or exits the app.

**Comment by cumany** [comment]
Try swiping the middle of the screen instead of swiping the edge of the screen

**Comment by pcause** [comment]
nope, same result

**Comment by luanlibao** [comment]
划右上角或者左上角是可以的
