### ISSUE TITLE
Dataview table line overflow for inline property

### ISSUE THREAD

**Issue by chauhan-utk** [whyt-byte/Blue-Topaz_Obsidian-css#239]
Having multiple inline property in data view table make the line go out of table boundary.

![image](https://user-images.githubusercontent.com/20888627/157489507-309d1463-bb6c-4cda-9d77-42acbea0411d.png)

Steps to repro:
1. Create note with multiple inline property like "summary::" in a note
2. Use Dataview query to render the property for note in a table.

```
TABLE summary WHERE summary != null
```

For single occurrence of inline property (like first row in screenshot), it renders correctly. However, if same inline property is use two or more times in a note, then it overflow.

The rendered table earlier used to properly wrap the line within table boundary. Now, after live preview update, the line overflow the table boundary.

**Comment by cumany** [comment]
#241  fixed
