### ISSUE TITLE
库名称的css有点问题

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#24]
更新了 0.9.22 版后，发现库名称那里会置顶显示，效果如图
![Snipaste_2020-12-15_09-17-03](https://user-images.githubusercontent.com/56058332/102155495-9afa5880-3eb6-11eb-914e-f636e8d8fd70.png)
![InkedSnipaste_2020-12-15_09-15-00_LI](https://user-images.githubusercontent.com/56058332/102155501-9cc41c00-3eb6-11eb-8429-c74093af1093.jpg)

**Comment by whyt-byte** [comment]
软件的bug，更新0.10.0就好了
![image](https://user-images.githubusercontent.com/72023275/102191515-7cb34d80-3ef4-11eb-8f5d-0c469066d019.png)
