### ISSUE TITLE
文件夹列表单行显示，增加文件名滚动效果 （2.3.3）

### ISSUE THREAD

**Issue by chenxin0397** [whyt-byte/Blue-Topaz_Obsidian-css#240]
效果不明显，文件夹还是换行显示

**Comment by chenxin0397** [comment]
![20210816135935011](https://user-images.githubusercontent.com/73974352/157589905-24280e29-9fea-481a-bd0a-13d81b4716e1.gif)
文件名滚动是为了在显示不全的情况下了解文件名是什么
让文件名全显出来才滚动的意义不大

**Comment by cumany** [comment]
#241 fixed
