### ISSUE TITLE
当 task 和 list 混用的时候，阅读视图的对齐参考线和文字显示位置不匹配

### ISSUE THREAD

**Issue by sqybi** [whyt-byte/Blue-Topaz_Obsidian-css#248]
WYSIWYG 编辑视图下是没有问题的，但是阅读视图会歪掉，如图：
![image](https://user-images.githubusercontent.com/966312/158550986-485c4699-82aa-49c4-ba05-e9e7cd9ea1f0.png)

看起来是文字显示歪了？

**Comment by sqybi** [comment]
在明亮模式下也有同样的问题

**Comment by whyt-byte** [comment]
已修复
