### ISSUE TITLE
请更新这里的样式

### ISSUE THREAD

**Issue by chenxin0397** [whyt-byte/Blue-Topaz_Obsidian-css#249]
/* ================================== */
/* ============== hider ============= */
/* ================================== */
/*adapted from minimal by @kepano*/
.hider-ribbon .workspace-ribbon-collapse-btn {
  display: none;
}
.hider-ribbon .workspace-ribbon.mod-right {
  pointer-events: none;
}
.hider-ribbon .workspace-ribbon.mod-left {
  position: fixed;
  border-right: 0px;
  margin: 0;
  height: 26px;
  overflow: visible;
  flex-basis: 0;
  bottom: 0;
  top: auto;
  display: flex !important;
  flex-direction: row;
  background: var(--background-primary);
  z-index: 17;
  opacity: 0;
  transition: opacity 0.25s ease-in-out;
}

.hider-ribbon .workspace-ribbon.mod-left .side-dock-ribbon-action {
  display: inline-block;
  padding: 5px 5px 0 12px;
}
更改前：
![20210816135935011](https://user-images.githubusercontent.com/73974352/158935771-cb736b13-0cfa-4610-b190-4810dbb1c1cf.gif)

更改后
![2021081613593500011](https://user-images.githubusercontent.com/73974352/158935803-dd9002b5-58cb-478c-9a13-c4a16825a748.gif)

**Comment by whyt-byte** [comment]
Fixed
