### ISSUE TITLE
Export PDF時，Table的字體太暗了

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#26]
表格的字體要變淡或列的背景要變：
![image](https://user-images.githubusercontent.com/131511/102859611-2bacd780-4467-11eb-86d8-6e96399d79db.png)

```
# Export PDF
## 表格測試
### 測試1

| 參數名 | 參數說明 |
| --- | --- |
| PARAM1 | 表示XXX使用 |
| PARAM2 | 表示XXX使用 |
| PARAM3 | 表示XXX使用 |
| PARAM4 | 表示XXX使用 |
| PARAM5 | 表示XXX使用 |
```

**Comment by whyt-byte** [comment]
done

**Comment by emisjerry** [comment]
黑底的字體應換成亮點的前景色。
![image](https://user-images.githubusercontent.com/131511/102946189-d9b59180-44fa-11eb-8b62-64c181c8f859.png)
