### ISSUE TITLE
有关表格的事情

### ISSUE THREAD

**Issue by xiaoshuichong** [whyt-byte/Blue-Topaz_Obsidian-css#260]
![image](https://user-images.githubusercontent.com/81357358/162112046-9d31a292-28e9-4885-bb53-bf817d3d7cd2.png)

如图，表格不会自适应填充，只是单纯地放在了左边。可以劳烦制作者在下次更新的时候加个自适应吗？

或者是我没找到方法？请求指点！

**Comment by cumany** [comment]
style setting 设置 2.3.8 设置表格不换行即可

**Comment by xiaoshuichong** [comment]
> style setting 设置 2.3.8 设置表格不换行即可

感谢，已设置成功。原来表格不换行是这意思呀，感谢！
