### ISSUE TITLE
主题名称如何隐藏

### ISSUE THREAD

**Issue by Doslin** [whyt-byte/Blue-Topaz_Obsidian-css#262]
![image](https://user-images.githubusercontent.com/29807388/162221998-9beb8549-4a74-4bb4-9d56-2e67b6f2bdf7.png)

**Comment by cumany** [comment]
1. style setting 2.3.7 更改
2. quickadd 插件 关闭 use  multi-line  input promt

**Comment by Doslin** [comment]
> 1. style setting 2.3.7 更改
> 2. quickadd 插件 关闭 use  multi-line  input promt

谢谢大佬
