### ISSUE TITLE
Obsidianv0.14.5中霞鹜文楷字体突然加载不出，电脑中已经安装

### ISSUE THREAD

**Issue by pullopen** [whyt-byte/Blue-Topaz_Obsidian-css#266]
原先使用一直很好，但是突然在一次重启后霞鹜文楷字体无法加载，变为默认的微软雅黑。重装字体、打开安全模式都没用。

不止是否与Obsidian自动更新有关，目前版本：v0.14.5

该字体在Word中确认可以使用，请问可能是什么原因？谢谢！

**Comment by whyt-byte** [comment]
因为新版本obsidian在设置面板中给了部分字体设置框。
主题暂时还没有跟进解决——同时满足style settings和默认字体设置。可以直接在：设置-->外观-->Font里输入 ”LXGW wenkai“。暂时解决这个问题。
完全适配要等几天，最近没什么空闲，见谅。
![image](https://user-images.githubusercontent.com/72023275/162780508-ea2fec63-4227-4d52-9cb4-446e32e09e29.png)

**Comment by zen010101** [comment]
这个临时解决方案不太完美。原来的效果可以做到 标题是雅黑，正文是霞鹜文楷，序号的阿拉伯数字也很好看，现在通过 Setting 这么一设，所有字体全部都变成霞鹜文楷了。

**Comment by zen010101** [comment]
推荐两个效果比较不错的字体：
1. [仓耳今楷01-W04 ](http://www.tsanger.cn/product/7)
2. [Sarasa Fixed Slab SC / 更纱黑体](https://github.com/be5invis/Sarasa-Gothic)

效果如下：
![仓耳今楷](https://user-images.githubusercontent.com/60574100/163109526-9924ee7c-d2de-4fd7-aa27-176d781a1cc3.png)


![Sarasa](https://user-images.githubusercontent.com/60574100/163109530-da8033df-7393-47a1-a3b2-d08939003acf.png)

**Comment by whyt-byte** [comment]
已修复，更新主题即可
