### ISSUE TITLE
Export PDF表格中，黑底的字體應換成亮點的前景色

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#27]
黑底的字體應換成亮點的前景色。
![image](https://user-images.githubusercontent.com/131511/102946189-d9b59180-44fa-11eb-8b62-64c181c8f859.png)

**Comment by whyt-byte** [comment]
改了一些，但是导出黑暗模式pdf颜色都会偏暗。再调整颜色会影响表格的观感，建议用明亮模式下导出pdf
![image](https://user-images.githubusercontent.com/72023275/103009253-68fd8c00-4571-11eb-896a-854e79a40849.png)

**Comment by whyt-byte** [comment]
已修正，将在下一个版本推出
