### ISSUE TITLE
建议明亮模式下，不同级别标签颜色区分度大一下，就像黑暗模式下一样。

### ISSUE THREAD

**Issue by ssmmtt** [whyt-byte/Blue-Topaz_Obsidian-css#270]
![QQ截图20220414104808](https://user-images.githubusercontent.com/16244320/163304079-3054337e-7321-4806-b7f0-1bb8f746bc9b.png)
![QQ截图20220414104829](https://user-images.githubusercontent.com/16244320/163304085-953e026a-d427-4a71-a4ea-86e83f2695bf.png)

**Comment by whyt-byte** [comment]
style settings插件中可自行设置标题颜色，默认的不做改动

**Comment by ssmmtt** [comment]
> style settings插件中可自行设置标题颜色，默认的不做改动

OK 多谢

**Comment by whyt-byte** [comment]
好的，希望你使用得愉快
