### ISSUE TITLE
对话窗变这样了

### ISSUE THREAD

**Issue by zen010101** [whyt-byte/Blue-Topaz_Obsidian-css#271]
Ob: 0.14.15 
Blue-Topaz: 20220413

部分对话窗变这样了（Command Palette，Quick Switch）窗口中似乎有了背景图案 ：

![微信截图_20220414163902](https://user-images.githubusercontent.com/60574100/163348337-77523540-311f-4bf7-aea6-3e9722233ca8.jpg)

但是，Setting 对话窗一切正常。

**Comment by whyt-byte** [comment]
这是个新特性，默认使用随机图片。可以在style settings 1.2.3 中进行设置
