### ISSUE TITLE
预览模式下代码没有高亮

### ISSUE THREAD

**Issue by iceice** [whyt-byte/Blue-Topaz_Obsidian-css#274]
编辑模式下：
<img width="736" alt="image" src="https://user-images.githubusercontent.com/17559521/163669792-6ab3223f-9fc7-42f5-92e9-bbe2afee57c8.png">

预览模式下：
<img width="693" alt="image" src="https://user-images.githubusercontent.com/17559521/163669801-3a675aa0-c589-49b1-9ddb-2c68577b2ff4.png">

**Comment by whyt-byte** [comment]
软件不识别“c++”，改为“cpp”即可
