### ISSUE TITLE
list去除box不彻底

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#28]
你好，我按css说明设置了去除list的box，但在list的左边还会有边框，希望可以彻底去除

![image](https://user-images.githubusercontent.com/56058332/103061878-84a37980-45e7-11eb-980e-eb7250a5facf.png)

**Comment by whyt-byte** [comment]
已经在TIPS里提供了4种可选样式，你只试了一种

**Comment by whyt-byte** [comment]
这边看起来清晰一些
https://forum.obsidian.md/t/theme-blue-topaz-v1-7-updated-20201209-for-v0-9-22/6425/27?u=whyi

**Comment by PaulHerrero** [comment]
解决了，在样式1里添加了 border-left: none !important; 去掉了左边的边框并保留了新版样式。
