### ISSUE TITLE
光标跟随的动态好奇怪，速度很慢，有没有取消这个动效？

### ISSUE THREAD

**Issue by skyue** [whyt-byte/Blue-Topaz_Obsidian-css#290]
![May-05-2022 15-35-54](https://user-images.githubusercontent.com/10450242/166880247-d21c0f89-bf80-4950-b5fa-65dbcb7d9db4.gif)
如gif所示

**Comment by whyt-byte** [comment]
这个难道不是你自己打开的功能嘛，关了就是了……😂

![image](https://user-images.githubusercontent.com/72023275/166882423-315d1ed9-1efb-4d56-8eed-01c09fe20419.png)
