### ISSUE TITLE
## 字体权重问题

### ISSUE THREAD

**Issue by Faith-YSQ** [whyt-byte/Blue-Topaz_Obsidian-css#297]
主题字体权重太高了，设置都更改不了，建议只更改默认字体，用户配置任然可以保留

**Comment by whyt-byte** [comment]
不好意思，我没有明白你的意思，我有以下疑问：

1. 你说的“设置”和“用户配置”分别指的是什么？
2. 更改不了字体指的是在哪里进行的更改——软件的外观选项里，还是style settings插件里？
3. 使用obsidian的环境是什么，软件版本是多少？主题uid是什么？
4. 由于obsidian软件的更新，现在的主题对字体的设置不适用于obsidian低于0.14.6及以下的版本（移动端1.2.0及以下），你提到的无法设置是否与软件、主题版本相关？

**Comment by Faith-YSQ** [comment]
额，好吧，我表述太笼统了
就是用这个主题之后，我之前再软件内设置-外观里面设置的字体有一部分失效了，好像只有普通段落的字体设置是有效的。
我用的版本是0.14.6

**Comment by Faith-YSQ** [comment]
我没有更改CSS代码，windows下的，最新的主题

**Comment by whyt-byte** [comment]
是的，主题对加粗等部分样式单独设置了字体，可以通过style settings插件进行细节更改
