### ISSUE TITLE
编辑模式下，点击标题最后位置，出现的光标位置不对

### ISSUE THREAD

**Issue by drrrMikado** [whyt-byte/Blue-Topaz_Obsidian-css#3]
问题如图：
![image](https://user-images.githubusercontent.com/11224565/95828366-7de6c380-0d67-11eb-99fe-a4a34307b10b.png)

**Comment by whyt-byte** [comment]
因为隐藏标题#造成的鼠标定位问题，暂时找不到解决办法。可以下载使用Asymmetric Blue Topaz （https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/tree/master/Asymmetric%20Blue%20Topaz），明亮模式下不隐藏#，算是一个折中方案。

**Comment by drrrMikado** [comment]
> 因为隐藏标题#造成的鼠标定位问题，暂时找不到解决办法。可以下载使用Asymmetric Blue Topaz （[点击查看](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/tree/master/Asymmetric%20Blue%20Topaz)），明亮模式下不隐藏#，算是一个折中方案。

好的
