### ISSUE TITLE
编辑页面引用块内文字选中问题

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#30]
在编辑页面使用 “>”引用一段文字，会自动渲染，此时用鼠标选中那段文字里的几个字时，会无法看到究竟选中了哪几个字

![Snipaste_2020-12-30_13-08-59](https://user-images.githubusercontent.com/56058332/103331345-7bf7eb00-4aa0-11eb-9017-c0b7b6124222.png)

**Comment by whyt-byte** [comment]
谢谢反馈，已改回原样
