### ISSUE TITLE
彩虹列表失效

### ISSUE THREAD

**Issue by williamlorder** [whyt-byte/Blue-Topaz_Obsidian-css#300]
新版里彩虹列表似乎又失效了

<img width="791" alt="截屏2022-05-13 18 59 13" src="https://user-images.githubusercontent.com/83387569/168269863-0260ee8d-2ed2-44d8-937a-647f83abbfe6.png">

**Comment by cumany** [comment]
新版ob已无法兼容 彩虹列表
建议编辑模式下 列表样式改为 using ob settings

**Comment by whyt-byte** [comment]
不再支持编辑模式下的彩虹大纲线。
