### ISSUE TITLE
暗色主题下，输出PDF，加粗字体颜色为白色

### ISSUE THREAD

**Issue by cangming99** [whyt-byte/Blue-Topaz_Obsidian-css#305]
暗色主题下，输出PDF，加粗字体颜色为白色，明亮主题下就没问题
![image](https://user-images.githubusercontent.com/85931842/168715633-67036e7b-012c-40ee-a1a4-bf9ea7ade650.png)

**Comment by cumany** [comment]
style settings  2.3.5 可以设置pdf导出 粗体颜色

**Comment by cangming99** [comment]
> style settings 2.3.5 可以设置pdf导出 粗体颜色

学会了，感谢！

**Comment by whyt-byte** [comment]
已调整导出默认颜色为黑色
