### ISSUE TITLE
目录显示异常 Directory display is abnormal

### ISSUE THREAD

**Issue by ning-JML** [whyt-byte/Blue-Topaz_Obsidian-css#31]
我很喜欢这个外观主题，但目录显示异常给我造成了一点困扰，希望能够修复一下，非常感谢。
I like this theme very much，But the abnormal directory display caused me a little trouble. I hope it can be fixed. Thank you.
![目录显示异常](https://user-images.githubusercontent.com/17660600/103460523-bcca5b00-4d51-11eb-9cde-b3f3278dba8c.PNG)

**Comment by whyt-byte** [comment]
昨天发布的版本已经修复了这个，请在社区主题内重新点击＂使用＂以更新，或者在release页面手动下载
