### ISSUE TITLE
请问mermaid时序图预览不能显示箭头，有办法吗

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [whyt-byte/Blue-Topaz_Obsidian-css#310]
箭头问题，ob默认主题也有这问题，但试了个其他主题没有。

**Comment by whyt-byte** [comment]
请提供更多信息，或者截图。我不知道mermaid图的种类，做复现挺麻烦的

**Comment by FinallyFinancialFreedom** [comment]
不好意思，信息没给全，代码如下：
```mermaid
sequenceDiagram
participant client
participant epoll
participant rbTree
participant rdlist
participant RedisReactor
participant Redis6

epoll ->> epoll : epoll_create()
client ->> epoll :TCP三次握手
epoll ->> rbTree : epoll_ctl()插入fd
rbTree ->> rdlist :ep_poll_callback()挂就绪fd(谁触发?)
RedisReactor ->> epoll :epoll_wait()阻塞调用
epoll ->> RedisReactor :拷贝rdlist值到用户空间
RedisReactor ->> RedisReactor :分发event,读写到handler,连接到acceptor
RedisReactor ->> Redis6 :IO 和执行命令分开线程.
```
这个例子，内容别管，不一定对，在预览模式时，调用线没有箭头，
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2133400/169484143-60006dfc-57bf-4b11-8e52-70f4646a7960.png">
但live preview时有，
<img width="438" alt="image" src="https://user-images.githubusercontent.com/2133400/169484224-3e8ed85e-95df-41a1-8db9-d03a62d4fce4.png">

**Comment by whyt-byte** [comment]
已复现，挺奇怪的问题。使用源码模式时，阅读模式是正常的。live preview的阅读模式是有问题的。
![image](https://user-images.githubusercontent.com/72023275/169485837-a4c49828-0e4c-4b45-9ff3-58d5245862ee.png)

我先找找原因

**Comment by whyt-byte** [comment]
我的判断是软件的问题，建议跟Obsidian开发者报个bug

**Comment by lichenbuliren** [comment]
> 

确实，在编辑模式下的实时预览是正常的，但是在 Preview  模式下就看不到箭头了，
在控制台调试看了下，edit  跟 prev 是两个 分开的 dom 节点，而里面的内容都是 svg 绘制的，还挺麻烦的

**Comment by whyt-byte** [comment]
Obsidian已修复此问题
