### ISSUE TITLE
请问这个该如何使用？

### ISSUE THREAD

**Issue by JunQu** [whyt-byte/Blue-Topaz_Obsidian-css#311]
作为刚入门的新手，我不是很确定它的使用方式。特别是我仔细的把文档读了三遍后，才在英文 发现这个确实是一个主题。
比较希望能把我这样的白痴用户给帮助起来，也便于分享，因为看了那么多图片，可是不知道怎么行动，我真的比较佩服那些一开始就能立马找到入口，然后把主题给用起来。可能他们看了一些文章？但是在这个仓库里我也没找到相关的文章链接。
顺便好奇为啥没有提交官方插件社区，那样使用起来就方便太多了，目前我只会点击安装来使用主题。
如果能够帮助我，非常感谢。

**Comment by cumany** [comment]
试试 示例库 里面有ob入门教程 
https://github.com/cumany/Blue-topaz-examples

整包下载后，解压到文件夹，然后用obsidian 以库的方式打开这个文件夹即可。
![image](https://user-images.githubusercontent.com/42957010/169481405-0e690012-2a09-43e6-8125-4151c6f4f632.png)

**Comment by whyt-byte** [comment]
你可以在软件的社区主题里找到Blue Topaz
![image](https://user-images.githubusercontent.com/72023275/169481395-3b5d8257-04f4-4b0a-94bb-055fb6b7dfe8.png)

如cuman所说，你可以尝试使用示例库来熟悉软件与主题的一些特性。

文档的话，在写了，完成时间不太确定。

**Comment by JunQu** [comment]
感谢回答，我尝试了一下，用上了这个主题，谢谢你们
