### ISSUE TITLE
flex形式移植出现显示问题。

### ISSUE THREAD

**Issue by PencilMing** [whyt-byte/Blue-Topaz_Obsidian-css#315]
![image](https://user-images.githubusercontent.com/82462283/170870293-fa15c622-0623-409a-aa7b-b47043fa02ba.png)
如图，想单独把admonitions的类型移植到新的库，新库也是bt主题。同时也复制了custom-admonition的css文件，但是到新的库上显示却变成这样。边上出现颜色断开的情况。不知道哪里出了问题。我也没有对callout相关的css，而且css全部关闭也是会出现这种情况。
然后原来库里显示的是颜色完全的。
![image](https://user-images.githubusercontent.com/82462283/170870303-220fc5bf-4775-46d8-b7bd-fb32ce983ac5.png)

**Comment by cumany** [comment]
已回答 https://github.com/cumany/Blue-topaz-examples/issues/27
