### ISSUE TITLE
Checkbox在编辑模式下渲染问题

### ISSUE THREAD

**Issue by np-22** [whyt-byte/Blue-Topaz_Obsidian-css#32]
未勾选时光标如果不在当前行时勾选框乱码：
<img width="131" alt="image" src="https://user-images.githubusercontent.com/10591164/103462897-5c99d180-4cdd-11eb-8952-a6f4ddc9ff5c.png">
<img width="175" alt="image" src="https://user-images.githubusercontent.com/10591164/103462903-63284900-4cdd-11eb-8d09-160d64ed6785.png">
勾选之后的状态没问题：
<img width="139" alt="image" src="https://user-images.githubusercontent.com/10591164/103462911-7804dc80-4cdd-11eb-99b6-fbf070115011.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/10591164/103462916-7d622700-4cdd-11eb-8d9d-d1d817346952.png">

**Comment by np-22** [comment]
新的vault里没有这个问题，估计是和其他的设置冲突了。

**Comment by whyt-byte** [comment]
> 新的vault里没有这个问题，估计是和其他的设置冲突了。

跟Show Whitespace插件冲突，关闭插件就行，暂时没找到共存的解决办法
