### ISSUE TITLE
请问如何取消或更改点击文档后的特效

### ISSUE THREAD

**Issue by wtfgfw1984** [whyt-byte/Blue-Topaz_Obsidian-css#320]
![image](https://user-images.githubusercontent.com/35790873/172100702-0df4ba0b-92b2-471a-9709-7ba880b2aa8c.png)
点击文档后，会先变成蓝色，然后变成红色，想改一下或者直接取消掉，不知道在哪设置。

**Comment by cumany** [comment]
关闭插件 Automatically Reveal Active File 即可

**Comment by wtfgfw1984** [comment]
> 关闭插件 Automatically Reveal Active File 即可

感谢！
