### ISSUE TITLE
装饰性光标失效

### ISSUE THREAD

**Issue by CASCfans** [whyt-byte/Blue-Topaz_Obsidian-css#324]
昨天更新了主题后，装饰性光标失效，只有在选择一段文字时才会出现。软件版本 0.14.6 和 0.14.15 都是这样
![image](https://user-images.githubusercontent.com/51940140/172743679-90a2cfb1-8a5c-4da9-ba37-037b28ca9224.png)
![image](https://user-images.githubusercontent.com/51940140/172743731-8a77f235-2d04-4113-8720-e5505fc0c327.png)

**Comment by whyt-byte** [comment]
软件升级导致的，已经标注了，只适合0.14.6版本软件。你说的0.14.6失效，可能是因为你开了自动更新

**Comment by CASCfans** [comment]
后续会修复吗，我暂时先退回去

> 软件升级导致的，已经标注了，只适合0.14.6版本软件。你说的0.14.6失效，可能是因为你开了自动更新

**Comment by whyt-byte** [comment]
软件更新改了光标显示方式，所以暂时没有修复方法

**Comment by CASCfans** [comment]
> 软件更新改了光标显示方式，所以暂时没有修复方法

请问有什么方法退回0.14.6吗，没有查到相关教程😄

**Comment by whyt-byte** [comment]
完全卸载并清除现有obsidian，需要使用一些卸载工具。然后使用0.14.6安装包重新安装
