### ISSUE TITLE
tag with _ are rendered strangely within tag-outline mode

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#326]
#my_day
![image](https://user-images.githubusercontent.com/15528506/172876173-8a4cd665-b2e8-40e7-a660-a6ef08721bd4.png)

#myday
![image](https://user-images.githubusercontent.com/15528506/172876337-25e0614c-cfdc-4dda-8800-67d5cfb0af51.png)

why there is a vertical bar?

**Comment by whyt-byte** [comment]
Fixed
