### ISSUE TITLE
Feature Request: line wrap for the tables

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#327]
The ITS theme supports line warp for the tables.

![image](https://user-images.githubusercontent.com/15528506/172895219-27a4f2c8-7760-49d9-a755-dbda3f4e667b.png)

But actually, I prefer Blue-Topaz Theme :D

Could you please support this feature in Blue-Topaz Theme?

**Comment by cumany** [comment]
I have pulled the request, just update the theme after the merge #328

**Comment by zhao414** [comment]
Great!
Thanks
