### ISSUE TITLE
想请教两个问题

### ISSUE THREAD

**Issue by link-ding** [whyt-byte/Blue-Topaz_Obsidian-css#33]
## 2 如何把 list 改回以前的版本 
已经使用了在reademe里面的取消box的方法, 但是那个点还是那种橙色的不太喜欢.
![image](https://user-images.githubusercontent.com/49264539/103472665-01063b80-4de4-11eb-9d1b-f7d5ee08b42c.png)

**Comment by whyt-byte** [comment]
先回答2

TIPS里提供了四种列表格式，包括之前的样式，你只试了一种。你可以逐个复制代码，做成css片段在软件中启用片段

**Comment by link-ding** [comment]
> 先回答2
> 
> TIPS里提供了四种列表格式，包括之前的样式，你只试了一种。你可以逐个复制代码，做成css片段在软件中启用片段

非常感谢,已经解决了第二个问题, 另外我看到在graph view里面的节点有不同的颜色 这个是如何做到的喃? 我现在的所有的节点都是蓝色的.

**Comment by whyt-byte** [comment]
关于图片缩放，正好我也想取消悬停放大功能，所以你现在更新主题就行了。

节点颜色，你开启相应按钮就行了
![image](https://user-images.githubusercontent.com/72023275/103479495-02962a80-4e09-11eb-8d1e-dfad20c82b1d.png)

**Comment by link-ding** [comment]
> 关于图片缩放，正好我也想取消悬停放大功能，所以你现在更新主题就行了。
> 
> 节点颜色，你开启相应按钮就行了
> ![image](https://user-images.githubusercontent.com/72023275/103479495-02962a80-4e09-11eb-8d1e-dfad20c82b1d.png)

非常感谢您的及时回答, 现在已经完全解决了我的问题
