### ISSUE TITLE
预览模式下段落间空行被删除问题

### ISSUE THREAD

**Issue by CASCfans** [whyt-byte/Blue-Topaz_Obsidian-css#332]
- 在实时编辑和源码模式下的空行，切换到预览模式下消失，使段落更紧凑，影响观看体验
- 设置中 2.2.4 开启阅读模式段间距已打开，但没有效果
![image](https://user-images.githubusercontent.com/51940140/173815211-ec926560-e27b-4aaa-ac80-1b3125245e4b.png)
![image](https://user-images.githubusercontent.com/51940140/173815704-115ac75d-992b-4370-864a-6dd41b771f1b.png)

**Comment by cumany** [comment]
obsidian md语法渲染的问题，默认主题也是这样。单个空格不会渲染，解决办法用全角空格。

**Comment by CASCfans** [comment]
> 上

收到，原来是这样，不过回车再输入全角空格稍显麻烦，还是继续使用吧，感谢解答😊

**Comment by cumany** [comment]
另外 设置的里的行间距 只是普通的段落行间距，你这里的间距准确的应该属于列表项间距。所以调节是没效果的
