### ISSUE TITLE
How to skip startup animation？

### ISSUE THREAD

**Issue by FongTsang** [whyt-byte/Blue-Topaz_Obsidian-css#334]
Dear whyt-byte, Is there any way to disable the startup animation(the circle and square) showed as the gif below.
![动画](https://user-images.githubusercontent.com/53118840/174946608-e958aa19-55eb-4e7c-a065-96215247b41a.gif)
.

**Comment by cumany** [comment]
#337   fixed!     select default in 2.3.16  with style  settings
