### ISSUE TITLE
不希望代码块换行是否能帮忙指导一下该如何操作

### ISSUE THREAD

**Issue by Chen-zihan** [whyt-byte/Blue-Topaz_Obsidian-css#336]
首先很喜欢你的主题，超级感谢~
然后有个小困扰
想要的样式：
1. 代码块内不自动换行
2. 代码块带有滚动条可以左右拖动
想在你的主题css文件里修改，但是不懂css，怎么改都无效。
在 Style Settings 插件中设置 【代码框】→【代码框换行】的钩去掉也不行。
期望的是像图片里这种~
![图片](https://user-images.githubusercontent.com/47914317/175124691-7e70fa70-7c3b-4399-9ecc-be112c2bc085.png)

**Comment by cumany** [comment]
之前的代码块换行设置只针对阅读模式生效。
#339  已提交功能，增加编辑模式代码块换行生效。

**Comment by mmmmmmmgo** [comment]
有没有办法, 制定有的代码块换行, 有的不用?

**Comment by cumany** [comment]
> 有没有办法指定有的代码块换行, 有的不用?

如果想这个笔记的代码换行就在yaml声明 cssclass: "code-wrap"
