### ISSUE TITLE
主题的流畅度不佳

### ISSUE THREAD

**Issue by zhaoliang0302** [whyt-byte/Blue-Topaz_Obsidian-css#340]
上下滑动有轻微卡顿的感觉，跟默认主题比有明显不跟手的感觉。请问需要怎么设置才能使性能最佳？

**Comment by dalecgu** [comment]
不是轻微卡顿，已经严重影响使用了。
最近的更新导致，使用过去的版本（比如 044f24fdf 这个版本）很流畅。

**Comment by zhaoliang0302** [comment]
> 不是轻微卡顿，已经严重影响使用了。 最近的更新导致，使用过去的版本（比如 [044f24f](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/commit/044f24fdfc7349aef151c646400645589533a66d) 这个版本）很流畅。

确实很卡，转minimal了

**Comment by cumany** [comment]
尝试如下操作看是否提高性能：
1. style  settings 设置 2.3.18 panne style 设置成 Traditional
2. 2.3.16  loading page style 设置为 default
3. 1.2.4 激活文件栏背景关闭
4. 3.6 dataview表格自动添加序号 关闭

**Comment by dalecgu** [comment]
对我来说第一项有效果，设置页面变流畅了；后面几项原本就没有打开。
顺便提下，dataview表格能否添加一个选项，决定hover的时候要不要放大该行？

**Comment by cumany** [comment]
> 对我来说第一项有效果，设置页面变流畅了；后面几项原本就没有打开。 顺便提下，dataview表格能否添加一个选项，决定hover的时候要不要放大该行？

2.3.8  表格选项 移除悬浮放大效果即可

**Comment by whyt-byte** [comment]
最好提升硬件配置，或者如cumany所述，关闭一些设置。

**Comment by cangjie2003** [comment]
您好，我导出PDF时，会卡白屏，之后跳转至PDF页面，这个问题有办法解决吗？
