### ISSUE TITLE
icon有误

### ISSUE THREAD

**Issue by eightHundreds** [whyt-byte/Blue-Topaz_Obsidian-css#341]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/18695431/175453157-275262bf-bb2b-4bbd-8d9d-1513f31c2ec8.png">
应该是一个眼镜/眼睛

**Comment by whyt-byte** [comment]
就是这么设置的，显示当前状态。

**Comment by whyt-byte** [comment]
不接受该逻辑，可以使用style settings切换默认图标。
