### ISSUE TITLE
改变编辑图标的颜色

### ISSUE THREAD

**Issue by batman47steam** [whyt-byte/Blue-Topaz_Obsidian-css#344]
![image](https://user-images.githubusercontent.com/36287035/176994943-cc226722-9949-48fc-9039-5769bb2ae938.png)

想请问一下，这个绿色图标编辑图标的颜色是在哪里改变啊，在style setting里面没找到

**Comment by cumany** [comment]
其实这个调用的是主题色 style setting 中2.1.2 主题色中修改
