### ISSUE TITLE
图片横排失效

### ISSUE THREAD

**Issue by xiaoshuichong** [whyt-byte/Blue-Topaz_Obsidian-css#346]
作者大大你好！我脱离bt新建一个库，何解图片不能横排，是哪里设置的嘛？感谢解答爱你哦😘

![image](https://user-images.githubusercontent.com/81357358/177733735-786fd2c6-f950-4813-b2f7-82cb72c77f15.png)

![image](https://user-images.githubusercontent.com/81357358/177733770-43c86df2-d2c4-4ab6-a8cc-92c1bd5e6f1c.png)

**Comment by xiaoshuichong** [comment]
附上我的文字：

> [!nowrap notitle]
![](https://git.poker/xiaoshuichong/VitaminE/blob/main/1.4lcyb71ts9s0.svg?raw=true)
![](https://git.poker/xiaoshuichong/VitaminE/blob/main/2.3wp79aug01u0.svg?raw=true)

**Comment by cumany** [comment]
请确保主题已更新到最新版本 20220622
