### ISSUE TITLE
I'd like to know how to change the font in the file.  I can't seem to find the code block for that.

### ISSUE THREAD

**Issue by brewha51** [whyt-byte/Blue-Topaz_Obsidian-css#35]

**Comment by whyt-byte** [comment]
You can change them in the css file:
![image](https://user-images.githubusercontent.com/72023275/103596901-efcf4300-4f39-11eb-9326-d9296ecefb78.png)

**Comment by brewha51** [comment]
Got it!  Also noticed that the expand / collapse arrow is missing from the search area?

![image](https://user-images.githubusercontent.com/76970520/103710248-32187480-4f7a-11eb-9a29-2700d2af4bac.png)

**Comment by whyt-byte** [comment]
> Got it! Also noticed that the expand / collapse arrow is missing from the search area?
> 
> ![image](https://user-images.githubusercontent.com/76970520/103710248-32187480-4f7a-11eb-9a29-2700d2af4bac.png)

I have fixed the bug in previous version, so you can update the theme either in Community Themes by clicking “use” button again in obsidian software, or download the css file in Releases page on Github and manually activate the theme.

**Comment by whyt-byte** [comment]
I am sorry that the last version caused the problem which I overlooked. Now I have fixed that. Thank you for your report.

**Comment by whyt-byte** [comment]
Fixed. Will be released in the next version. Thank you.
