### ISSUE TITLE
[Bug] embed item with wrong height

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#350]
To reproduce the bug:

1. create a new note 
2. create a list item and make a embed link pointing to this item with ^
3. embed the link above using ![[]]
4. call command "open current pane in new window" and compare the embed items in the new windows.

Expected:
embed item is shown in an embed area whose height is adaptive to the content.

Actual:
an embed area is shown with a very large height.

(in the following image: left is the pop-up new window, right is the original built-in window of Obsidian)

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/15528506/178199924-a3835e45-a0ed-48a3-803f-aabffe984682.png">

I tried the sandbox, it works fine. So I guess it may be an issue of the theme.

**Comment by cumany** [comment]
并没有复现出这样的问题， 尝试在style setting 中2.3.6 设置嵌入高度试试

**Comment by zhao414** [comment]
别介意。不是主题的问题。我误判了。sorry
