### ISSUE TITLE
更新之后，旧的配置没了？

### ISSUE THREAD

**Issue by xibaibai9527** [whyt-byte/Blue-Topaz_Obsidian-css#352]
当初是用了好久之后才配置好的，今天obsidian更新了新版本，一些线条乱了，就来更新蓝宝石的新版本，但是当初配置好的东西都消失了，字体，主标题下的漂亮的横线，还有一大堆我没来得及看的东西

我用了 Style Settings 自带的 Import 功能，想找回原来的设置，也不行。

只能手动再改一遍吗？当初我可是一个个改了大半天的

**Comment by whyt-byte** [comment]
不清楚具体情况，以下都是猜测：
可能之前的版本太旧，主题更新后部分设置不兼容。
以为不清楚情况，所以也暂无解决办法。

设置好以后可以导出一份备份。
