### ISSUE TITLE
filename not wrap in file panel

### ISSUE THREAD

**Issue by FongTsang** [whyt-byte/Blue-Topaz_Obsidian-css#355]
Dear Developer, I prefer filename in the file panel display only in one line but the default setting of blue topaz is word-wrap, so I use the snippet below:
```
.nav-file-title,
.nav-folder-title {
  white-space: nowrap;
  width: auto;
  overflow: hidden;
}
```
but there comes another question, when a filename or folder name is too long, the panel can't display the front content,like that:
![图片](https://user-images.githubusercontent.com/53118840/181407989-4565d259-ab4f-41b7-ac34-e0ece8b6fa90.png)
I try to change "hidden" into  "scroll" in the overflow, but final result is not what I want. Is there any way to add a scroll bar for the whole file panel instead of for each file name?
Thanks.

**Comment by cumany** [comment]
turn on the 2.3.3 option In the style settings plugin,  filename styles and select  file name  scrolling when hovering
