### ISSUE TITLE
并排显示图片情况下在阅读视图中无法显示图片

### ISSUE THREAD

**Issue by acrobatman** [whyt-byte/Blue-Topaz_Obsidian-css#356]
我在obsidian的论坛上提了一个bug，开发人员回复说obsidian不支持Blue Topaz的并排显示图片模式，详情参考：https://forum.obsidian.md/t/image-in-live-preview-and-reading-view-are-different/41232

麻烦作者看一下怎么解决这个问题，这个问题在使用File Cleaner插件的时候会有问题，导致这些并排显示的图片当做未引用的图片清理掉；

**Comment by cumany** [comment]
应该是跟某些插件冲突 阅读模式平铺 样式已修复 更新主题即可 #362
