### ISSUE TITLE
Automatic counting missing match between edit and preview mode when using  colourful note

### ISSUE THREAD

**Issue by mizzouxie** [whyt-byte/Blue-Topaz_Obsidian-css#36]
So appreciate you provide such a beautiful and functional theme, only find a tiny bug.

Automatic counting miss matched between edit and preview mode when using  colourful note 
![image](https://user-images.githubusercontent.com/77134369/103967678-19e65800-5128-11eb-83be-74a1ba1adfb5.png)

**Comment by whyt-byte** [comment]
Thank you for liking it. I will try to deal with it. Thank you for reporting.

**Comment by whyt-byte** [comment]
The list-style has been changed in the next version. And the automatic counting has been cancelled.
