### ISSUE TITLE
与Quiet Outline插件样式冲突

### ISSUE THREAD

**Issue by cangming99** [whyt-byte/Blue-Topaz_Obsidian-css#371]
用Blue-Topaz后，Quiet Outline插件的样式没了，好像是最近更新了Blue-Topaz才出现的，有什么解决办法吗
使用Blue-Topaz主题：![image](https://user-images.githubusercontent.com/85931842/184560225-3fe4c6a0-8ef6-4620-9f1f-23ff69a13c9f.png)

使用默认主题：![image](https://user-images.githubusercontent.com/85931842/184560239-0dd81b55-a314-403f-8153-f77995b02955.png)

**Comment by cumany** [comment]
3.11 中关闭即可 #373
