### ISSUE TITLE
The task field  displaying weirdly

### ISSUE THREAD

**Issue by danieltomasz** [whyt-byte/Blue-Topaz_Obsidian-css#38]
Really nice theme!

I have only problem with  the how the "not yet  done" characters are displaying in the edit mode

![image](https://user-images.githubusercontent.com/7980381/104232304-727f6300-5450-11eb-9291-f2feef42069a.png)

What I mean is this 
```
- [ ] task 1
- [ ]  task 2 
```

- [ ] task 1
- [ ]  task 2

**Comment by whyt-byte** [comment]
Thank you for using the theme. The theme conflicts with the plugin "Show Whitespace". And unfortunately, I didn't find a way to deal with it. Please also find here: https://github.com/deathau/cm-show-whitespace-obsidian/issues/2
