### ISSUE TITLE
Bold text disappear when exporting to PDF from dark mode (and the quotes look bad)

### ISSUE THREAD

**Issue by psyguy** [whyt-byte/Blue-Topaz_Obsidian-css#39]
Hi,

Thanks for this nice theme!

The issue is what the title reads. to make a comparison, here is the export in the light mode:

![image](https://user-images.githubusercontent.com/8527082/105898619-f1ac9380-6019-11eb-8749-165d3820a0b1.png)

But it is exported like this in dark mode

![image](https://user-images.githubusercontent.com/8527082/105898473-c32eb880-6019-11eb-8345-a3b38c5c12f6.png)

(I saw similar issues on this #26, #27 already.)

**Comment by whyt-byte** [comment]
Thank you for your reporting. Now it is fixed and will be released in the next version.
