### ISSUE TITLE
in Obsidian 0.16.0, bullet list dot looks weird

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#393]
![image](https://user-images.githubusercontent.com/15528506/187496762-86d7f12f-efa3-4afc-ab46-9791296804c9.png)

**Comment by ernestyao** [comment]
似乎是整个文件目录栏+编辑区都往左上偏移了半格，文件目录侧边栏的展开、合并箭头和文字也是重叠的

**Comment by whyt-byte** [comment]
主题不会支持v0.16

**Comment by jason20211010** [comment]
真的太可惜了，我打從心裡覺得其他主題的美感完全不能和你的主題相比，甚至可以說是天與地的差別，感謝你的付出。
