### ISSUE TITLE
Thanks letter!

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#395]
听闻不再支持 0.16.x，很是遗憾。

感谢 Blue-Topaz 这么长时间以来的陪伴，让我在 Obsidian 使用中，心情愉悦，事半功倍！

祝好！

**Comment by cumany** [comment]
感谢支持 承蒙厚爱。
Blue topaz 0.16.x 适配工作正在进行中

**Comment by whyt-byte** [comment]
谢谢支持，主题已经基本支持了v1.0
#407
