### ISSUE TITLE
Task icons for [>] and [<] are swapped

### ISSUE THREAD

**Issue by asphaltbuffet** [whyt-byte/Blue-Topaz_Obsidian-css#396]
The icons rendered for a task completed with [>] or [<] are incorrect. They point in the opposite direction.

### Observed
```markdown
- [>]  checked with `>`
- [<] checked with `<`
```
![image](https://user-images.githubusercontent.com/30903912/189499950-09e083d2-7113-40f7-b223-042cb7dd6085.png)

**Comment by whyt-byte** [comment]
Thank you for your report and debugging!
