### ISSUE TITLE
在F11全屏模式下，深色背景滚屏时出现阴影问题

### ISSUE THREAD

**Issue by CaoZihang** [whyt-byte/Blue-Topaz_Obsidian-css#399]
非全屏或亮色模式全屏都没有问题，阴影会在几秒种后消失
![1](https://user-images.githubusercontent.com/64113110/190839525-09459beb-ceca-441f-bb74-68b96f53b3c3.jpg)

**Comment by CaoZihang** [comment]
是背景设置-工作页面背景开启时产生的问题

**Comment by cumany** [comment]
#402
