### ISSUE TITLE
编辑模式下引用渲染有问题

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#4]
![image](https://user-images.githubusercontent.com/56058332/96138440-5b53d680-0f30-11eb-99f2-a4426c54e9ba.png)
![image](https://user-images.githubusercontent.com/56058332/96138487-66a70200-0f30-11eb-93d7-585c1aea4a34.png)

**Comment by whyt-byte** [comment]
不太明白哪里有问题，如果是说从上到下的引用框标识，空一行就行了。或者说你想要下面这种对齐？

![image](https://user-images.githubusercontent.com/72023275/96230405-06649e80-0fca-11eb-9944-e2f3df732c2b.png)

如果是想要对齐，打开css，找到下面代码（1557行），把margin-left的5px改成0px就行。

```
div:not(.CodeMirror-activeline)>.HyperMD-quote {
  border-left: 7px solid var(--ztys);
  margin-left: 5px;
}
```

**Comment by PaulHerrero** [comment]
![Snipaste_2020-10-16_16-26-43](https://user-images.githubusercontent.com/56058332/96234778-783de780-0fcc-11eb-86ea-423433b77472.png)
就是这个意思

**Comment by whyt-byte** [comment]
引用完，空一行，分割线跟下面的文字再空一行

**Comment by PaulHerrero** [comment]
感谢，已解决
