### ISSUE TITLE
在文章顶部再按一下Page Up会使侧边栏消失,重启才能恢复

### ISSUE THREAD

**Issue by ZoroGH** [whyt-byte/Blue-Topaz_Obsidian-css#404]
下图为全屏截取的,侧边栏左边的一列按钮已经几乎看不见,同时在最右侧出现了这个收起按钮.
就是当写文章按住`Page Up`翻到最上面之后,再按一下`Page Up`就会出现这种情况
![image](https://user-images.githubusercontent.com/67215466/193601271-369e9d89-1e96-455e-9acf-b32fd06dd2a0.png)

**Comment by whyt-byte** [comment]
请查看style settings 1.3里的相关样式

**Comment by ZoroGH** [comment]
> 请查看style settings 1.3里的相关样式

在我产生这个BUG时我还没有安装Style Setting 插件, 我切换验证了一下,发现Ob默认的主题不会出现这个问题

**Comment by ZoroGH** [comment]
> > 请查看style settings 1.3里的相关样式
> 
> 在我产生这个BUG时我还没有安装Style Setting 插件, 我切换验证了一下,发现Ob默认的主题不会出现这个问题

问题解决了, 解决办法是在Style Setting插件1.3节将右侧侧边栏样式选择为fixed即可.感谢群聊以及开发者们,辛苦了
