### ISSUE TITLE
Theme broken with Obsidian 1.0.0

### ISSUE THREAD

**Issue by eikowagenknecht** [whyt-byte/Blue-Topaz_Obsidian-css#407]
The theme looks broken in various ways in Obsidian v1.0.0. Is there any plan to fix this?

**Comment by cumany** [comment]
working on

**Comment by Ali-C-Ila** [comment]
It's even more broken now that v1.0.0 has updated the UI significantly.

**Comment by whyt-byte** [comment]
> It's even more broken now that v1.0.0 has updated the UI significantly.

It's caused by the new version, not the theme. So you shouldn't come to blame us. By the way, the beta version Blue Topaz Theme has been released, but only available in Topaz Community.

**Comment by romenello** [comment]
cannot find blue-topaz in the theme manager.

**Comment by eikowagenknecht** [comment]
> cannot find blue-topaz in the theme manager.

If you use Obsidian 1.0 that is because it only shows themes that have been updated to be compatible again.

**Comment by kchen0x** [comment]
looking forward to the new compatible version~

**Comment by Raynard-Swanepoel** [comment]
![image](https://user-images.githubusercontent.com/48661996/195996855-23c8574a-8916-4cec-ae38-a12dc7f49835.png)

**Comment by Raynard-Swanepoel** [comment]
This is my favourite theme. Hope you guys have a chance to make some fixes. Thanks anyways.

**Comment by chasoft** [comment]
This is my favorite theme! It's broken in ver1.0, but I'm still using this theme… Love its color, font size and font style.

**Comment by whyt-byte** [comment]
Thank you for being so supportive. You may update Blue Topaz in Obsidian or find the 'theme.css' on the Code page. Although It's still a beta version now, which means it may have some unfixed things or bugs, I recommend updating the theme and having a try.
