### ISSUE TITLE
主题自动跳转回默认主题？

### ISSUE THREAD

**Issue by simon1uo** [whyt-byte/Blue-Topaz_Obsidian-css#409]
最近在使用 Obsidian 过程中，主题突然会自动切换成默认主题或者其他主题，而使用其他主题没有出现这样的问题？？而且 Blue-Topaz 主题也不能下载到本地应用？

我的 Obsidian 版本是 v0.15.9

这是刚刚手动切换回 Blue Topaz 的界面：

![](https://s2.loli.net/2022/10/11/avMBn8wd4Kl1YHN.png)

过了一段时间之后，自动切换回默认主题：
![](https://s2.loli.net/2022/10/12/DgfWEKxZcVHhGNy.png)

**Comment by whyt-byte** [comment]
没有遇到过这种情况，可以尝试关闭插件进行排查。
主题的颜色跟默认设置不同，如果不是你改动的话，也可以检查主题的存放位置，非“theme”文件夹下不要出现obsidian.css文件

**Comment by simon1uo** [comment]
找到原因了😳因为一直用的 iCloud 同步的笔记仓库，iCloud 开启了优化存储空间，导致隔一段时间就主题文件就因为「优化」丢失，搞得 Obsidian 没有找到主题的 CSS 文件。

**Comment by yangcht** [comment]
请问是在哪里关闭优化存储空间？我的macOS上的obsidian也遇到了类似的情况。Blue Topaz的主题总是被自动清除。

**Comment by simon1uo** [comment]
> 请问是在哪里关闭优化存储空间？我的macOS上的obsidian也遇到了类似的情况。Blue Topaz的主题总是被自动清除。

在 Apple ID 的设置中，具体看下图：
![](https://s2.loli.net/2022/12/26/r4MHFWwiLKQYOVX.png)
