### ISSUE TITLE
大纲的箭头无法动态显示

### ISSUE THREAD

**Issue by innuaa** [whyt-byte/Blue-Topaz_Obsidian-css#41]
如图：
![image](https://user-images.githubusercontent.com/64938861/106376779-4b72dc00-63d3-11eb-91a3-6882afa2bb31.png)
![image](https://user-images.githubusercontent.com/64938861/106376785-53cb1700-63d3-11eb-8fb4-dc5079099ea5.png)

**Comment by whyt-byte** [comment]
在改了，在改了

**Comment by whyt-byte** [comment]
Done
