### ISSUE TITLE
double bullet dot in edit mode for Obsidian v.1.0?

### ISSUE THREAD

**Issue by whytong** [whyt-byte/Blue-Topaz_Obsidian-css#410]
After Obsidian upgraded to v.1.0. I noticed the unordered bullet list showing two dots in the `editing` mode but not the `reading` mode. 
The grey dot seems to come from Obsidian that I cannot change, and the color of the black dot can be changed in the style settings. 
![bluetopaz](https://user-images.githubusercontent.com/54590532/195970542-aa965ea5-c918-4723-9b91-0b3bd915b068.jpg)

**Comment by pennpeng** [comment]
+1

**Comment by whyt-byte** [comment]
In the beta version, which is currently only available in the Topaz Community, this issue has been fixed.
