### ISSUE TITLE
Advanced Tables doesn't maintain table formatting

### ISSUE THREAD

**Issue by bjcbmi** [whyt-byte/Blue-Topaz_Obsidian-css#415]
Hi,
Noticed an issue that've I've been unable to overcome.

When editing a table, the Advanced Tables Plugin has an option to "Pad cell width using spaces" which formats the tables to make them easier to read when editing.

When using other themes this works, however with Blue Topaz it doesn't seem to allow the extra spaces.  Below are screenshots on the difference between themes.

**Example in Blue Topaz**
![sample-blue-topaz](https://user-images.githubusercontent.com/115983501/196135565-29961d17-1c24-45a2-bb8f-5b9d111c5e90.png)

**Example in other theme**
![sample-working](https://user-images.githubusercontent.com/115983501/196135574-2c1422ad-7efa-4fd3-97d1-f83b0f65e0de.png)

Is there any way this could be resolved?  Love the theme, this is the only thing that becomes a little annoying when editing tables.

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/196143077-f0cc033d-05ab-4dde-a068-5752bda48806.png)
I did not reproduce your problem, maybe it is related to the font, try to change the font or set Obsidian default font  with  style  setting  2.2.1

**Comment by bjcbmi** [comment]
Thanks @cumany.  I tried a number of things but not the font.  I reset the font field back to the default and you're right it worked.  

I then set it back the way it was and it still works.  Not sure what happened initially but it is all good now.  

Appreciate it, solved the only issue I was having with the theme.
