### ISSUE TITLE
打印无法正确显示加粗斜体字符

### ISSUE THREAD

**Issue by ArcticHayasi** [whyt-byte/Blue-Topaz_Obsidian-css#417]
![Snipaste_2022-10-18_16-58-13](https://user-images.githubusercontent.com/67898994/196450794-014ab2c5-3b4e-4020-894e-d78cf8994928.png)
如图。只能显示出色块。

* 修正，标题指export to pdf。

**Comment by whyt-byte** [comment]
PDF阅读器的问题，可以换一个软件，例如Adobe Acrobat
