### ISSUE TITLE
Emoji rendering in recent app versions

### ISSUE THREAD

**Issue by lwb52** [whyt-byte/Blue-Topaz_Obsidian-css#42]
emojis that appeared in one line in edit mode also used to render on one line in preview mode, but in 0.10.11/12/13 now render on a new, separate line, which is /not/ wanted:

example edit—
”work⏬test”

example preview—
”work
⏬
test"

**Comment by whyt-byte** [comment]
Fixed. Thank you for reporting.

**Comment by lwb52** [comment]
thanks for fixing! if I may: what did you do? I’d like to apply this fix to other themes that have the same issue… ;^)
