### ISSUE TITLE
Add a Style Settings for changing the code block copy button

### ISSUE THREAD

**Issue by linqingyao** [whyt-byte/Blue-Topaz_Obsidian-css#425]
![image](https://user-images.githubusercontent.com/83944508/197146593-b12ffe8c-2cac-4542-9373-3b68867464d9.png)
Change-->
![image](https://user-images.githubusercontent.com/83944508/197146761-aae9123c-b7eb-4892-bda6-718ec2ffb418.png)

**Comment by whyt-byte** [comment]
Please be polite.

**Comment by linqingyao** [comment]
What's so bad about being polite? I shouldn't have posted the image (I think the title itself says what I want to add)

**Comment by whyt-byte** [comment]
I'm sorry to find that you don't know what it means to be polite.

**Comment by cumany** [comment]
“给我把代码块图标换了，就换成这样“
“请礼貌一些”
“为什么让我礼貌？难度我发的图片不够礼貌吗？”

让开发者做事情，还用这种语气，鬼才干

**Comment by linqingyao** [comment]
非常抱歉，词典翻译和自己表达的意思太不一样了
