### ISSUE TITLE
預覽狀態下，折疊符號太靠近文字

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#43]
↓ 和文字間應有空間。

![image](https://user-images.githubusercontent.com/131511/107368626-baf77280-6b1b-11eb-96af-e2dbea92b7cf.png)

**Comment by whyt-byte** [comment]
无法复现

**Comment by emisjerry** [comment]
以下快照不知是否有幫助？我是直接套用Blue Topaz，並未修改任何樣式，已啟用安全模式關閉所有插件，CSS Snippets皆未啟用。

![image](https://user-images.githubusercontent.com/131511/107502842-2c92f780-6bd4-11eb-8278-0075a48d8f04.png)

**Comment by emisjerry** [comment]
試出癥結點了：若仍勾選【套用自訂CSS】時摺疊符號會非常靠近標題文字，取消勾選就正常了。

![image](https://user-images.githubusercontent.com/131511/107514066-1bea7d80-6be4-11eb-89bf-3d30ad1a575e.png)

**Comment by whyt-byte** [comment]
是的，新的主题启用位置在.obsidian>themes里，放在之前的位置会出现各种问题，最好关闭。
