### ISSUE TITLE
光标在编辑模式下悬停在待编辑区域或者链接时无法正常转变为编辑模式的“I”图标，最直接的影响就是open under link under cursor in new tab的快捷键。 

### ISSUE THREAD

**Issue by Chase518** [whyt-byte/Blue-Topaz_Obsidian-css#437]
最直接的影响就是open under link under cursor in new tab的快捷键，按住默认的control快捷键点击链接无反应。
换为其他主题或默认主题则正常使用。自己新建一个测试库也存在此问题，最奇怪的是从GitHub上下载的主题样例库却能正常使用。

**Comment by cumany** [comment]
2.3.11  
![image](https://user-images.githubusercontent.com/42957010/199474251-d49b8e9a-fc3f-45d3-9b94-77ab2517810e.png)
试下这个选项

**Comment by Chase518** [comment]
> 2.3.11 ![image](https://user-images.githubusercontent.com/42957010/199474251-d49b8e9a-fc3f-45d3-9b94-77ab2517810e.png) 试下这个选项

谢谢谢谢(*￣︶￣) 
之后主题又出更新了，我更新以后就没事啦~ 如果再出现我再试试~~
