### ISSUE TITLE
Preview mode and Editor mode position are mismatch.

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#44]
Hi, 

Happy Chinese Spring Festival.

Thank you for providing us a colorful css for Obsidian.

I'd like to report an issue.

To reproduce the issue:

in the editor,  create a note with the following content 
```
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10

some text1

- somthing - something
- somthing - wrong
	- somthing - something
		- gggg
		- kkkk
		- kkkkkkk
	- somthing - something
	- somthing - something
- somthing - something
- somthing - something
```

Split the window vertically and then turn on the preview mode in one of the split windows(panel) and link the two panels(the edit mode panel and the preview-mode panel)

Now make the editing mode window(panel) the active window(panel), and scrolled down. 

When the text "something-wrong" moves to the top of the edit panel, you will find in the preview panel the view moves quickly back to the top of the page.

Turning off the custom CSS will fix the issue, so I think this one is related to your .css.

Moreover, this is not a new issue. I've been using a .css file modified based on your .css file since last Oct. This issue was there since that time. Hope this information would be helpful for you to locate the problem.

Looking forward to your reply.

**Comment by whyt-byte** [comment]
Happy CNY!

Thank you for your information. Reproduced, will check later.

**Comment by whyt-byte** [comment]
Have Fixed. Will be released in the next version.

**Comment by zhao414** [comment]
Thank you!
What number is the next version?

**Comment by whyt-byte** [comment]
v2.1

**Comment by zhao414** [comment]
Is there a quick fix that I can apply right now or can you provide some clues on how to tweak the css file by myself?

**Comment by whyt-byte** [comment]
When I close the issue, I have finished the fix. And you can click 'use' in Community Themes of Obsidian to update.
