### ISSUE TITLE
When the width of the code is too long, it is easy to collapse to the second line

### ISSUE THREAD

**Issue by bingryan** [whyt-byte/Blue-Topaz_Obsidian-css#440]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/41174435/199532669-2b6d6de7-5ef6-42dc-9453-f9652e79154a.png">

```rust
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self.kind {
            ErrorKind::Msg(ref message) => write!(f, "support issue: https://github.com/xxxx/xxxxx/blob/master/primitives/core/src/error.rs"),
            ErrorKind::Io(ref e) => write!(f, "{:?}", e),
            ErrorKind::Hex(ref e) => write!(f, "{:?}", e),
            ErrorKind::Utf8(ref e) => write!(f, "{:?}", e),
            ErrorKind::FromUtf8(ref e) => write!(f, "{:?}", e),
        }
    }
}
```

**Comment by whyt-byte** [comment]
You may find the related setting options in the Style Settings plugin.

**Comment by bingryan** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/41174435/199635559-e0442225-1482-4884-b2ba-9eb1671d382e.png">
BTW, with the existing settings, the visual effect is not very good. Compared with the codebox on github, the visual effect of the overall code movement on github is better.
