### ISSUE TITLE
[FR/suggestion] please add code highlighting theme setting

### ISSUE THREAD

**Issue by bingryan** [whyt-byte/Blue-Topaz_Obsidian-css#441]
code highlighting can be set:

![Ruby Code in Tomorrow Night](https://github.com/chriskempson/tomorrow-theme/raw/master/Images/Tomorrow-Night.png)
![Ruby Code in Tomorrow](https://github.com/chriskempson/tomorrow-theme/raw/master/Images/Tomorrow.png)
![Ruby Code in Tomorrow Night Eighties](https://github.com/chriskempson/tomorrow-theme/raw/master/Images/Tomorrow-Night-Eighties.png)
![Ruby Code in Tomorrow Night Blue](https://github.com/chriskempson/tomorrow-theme/raw/master/Images/Tomorrow-Night-Blue.png)
![Ruby Code in Tomorrow Night Bright](https://github.com/chriskempson/tomorrow-theme/raw/master/Images/Tomorrow-Night-Bright.png)

link: https://github.com/chriskempson/tomorrow-theme

**Comment by bingryan** [comment]
I mean the code highlighting theme is set separately from the obsidian appearance theme

**Comment by whyt-byte** [comment]
Welcome PR

**Comment by cumany** [comment]
#444  update  theme
