### ISSUE TITLE
latex多行公式显示问题

### ISSUE THREAD

**Issue by Sun-Jiahao** [whyt-byte/Blue-Topaz_Obsidian-css#442]
我想要使用：`$$\overline{x}$$`来得到x平均值的符号，但是发现x上面的一横不见了，尝试使用`$$\overline{y}$$`发现是可以的，同时我也发现，改变字体的大小能够解决这一问题。

**Comment by cumany** [comment]
这是ob的通病，就算是默认主题 你调整字体大小 或者ctrl 滚动鼠标 这个横线也会消失。默认主题字体设置到17 就会消失横线。Bt主题设置字体大小在14的时候会消失横线。

**Comment by Sun-Jiahao** [comment]
好的，谢谢你！
