### ISSUE TITLE
[bug] 鼠標浮在backlink選項上的時候，按鈕會狂閃而且對按下沒反應

### ISSUE THREAD

**Issue by Ali-C-Ila** [whyt-byte/Blue-Topaz_Obsidian-css#450]
edit: For English users, this issue is about flickering buttons in the in-document "linked mentions" section. They flicker at high rates and fail to function.

鼠標浮在backlink的四個選項上的時候，按鈕圖示會狂閃而且按下時有80%的機率按鈕會沒反應
(想像以一秒十次的頻率在下兩張圖之間閃爍)
![image](https://user-images.githubusercontent.com/56729449/201868961-73b011c5-6f09-47b6-8cb0-4bcbc71302fa.png)
![image](https://user-images.githubusercontent.com/56729449/201868998-ff4712eb-80c1-41a6-9357-c73426cdd13f.png)

- 側邊欄則無此現象
- iOS 版也有類似問題

## debug info
完全使用預設設定，安全模式
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz
	Snippets enabled: 0
	Restricted mode: on

**Comment by Ali-C-Ila** [comment]
另一個閃動過程中的截圖
![image](https://user-images.githubusercontent.com/56729449/201871221-536fcecd-a9d6-4763-8da8-3465bced830a.png)

**Comment by cumany** [comment]
2.3.14

![image](https://user-images.githubusercontent.com/42957010/202824621-694739a9-0e9e-41da-af59-0ab29a3a68dd.png)

**Comment by Ali-C-Ila** [comment]
三格選項各自開啟、同時開啟、開啟再關閉，重新啟動obsidian都試過了，無效(沙盒模式中也無效)
![image](https://user-images.githubusercontent.com/56729449/202836665-7163caf6-b01e-4f1b-819f-3416e2ed997f.png)

**Comment by Ali-C-Ila** [comment]
@cumany 想請問一下是只有我遇到這個問題嗎? 既然在沙盒模式中都能重現了，我以為這應該是個全面性的問題?
Am I the only one encountering this problem?

**Comment by Ali-C-Ila** [comment]
使用styles settings 2.3.14成功解決問題，謝謝開發者的用心❤️



不過順便提一下，不使用style settings 的情況下此問題還是存在
## Reproduce steps
1. 重新啟動obsidian
2. 建立一個新的沙盒
3. 打開 in-document backlink
4. 安裝 blue topaz
5. 游標移到 indocument backlink的四個按鈕上，可見按鈕一直閃爍而且有時候按了沒反應
![image](https://user-images.githubusercontent.com/56729449/203706521-9a3f2021-28ea-4f61-9333-b9bf61fb4ced.png)

## debug info
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz
	Snippets enabled: 0
	Restricted mode: on

**Comment by cumany** [comment]
因为这个选项默认值是有图标动画

**Comment by acrobatman** [comment]
我也有这个问题，“折叠搜索结果”这个按钮悬浮上去，提示信息会一直闪烁，点击的话要多点击几次才生效
主题是今早上刚刚更新的；

**Comment by acrobatman** [comment]
> 我也有这个问题，“折叠搜索结果”这个按钮悬浮上去，提示信息会一直闪烁，点击的话要多点击几次才生效 主题是今早上刚刚更新的；

在主题设置里面开启“”

**Comment by Ali-C-Ila** [comment]
Appears to be completely fixed, rainbow color can render correctly now.
