### ISSUE TITLE
可否增加一个 全局复制按钮

### ISSUE THREAD

**Issue by A2Data** [whyt-byte/Blue-Topaz_Obsidian-css#453]
类似： http://editor.md.ipandao.com/examples/full.html 
https://md.openwrite.cn/
编辑完成之后，可以直接复制，方便发布其他平台

**Comment by cumany** [comment]
发错地方了吧  应该发到这个插件的issue里
https://github.com/cumany/obsidian-editing-toolbar

**Comment by A2Data** [comment]
哈哈哈 好像是 好的，我发过去
