### ISSUE TITLE
在文字后面添加emoji，预览时emoji会换行显示

### ISSUE THREAD

**Issue by geekmai** [whyt-byte/Blue-Topaz_Obsidian-css#46]
如题
编辑
![gtvTij](https://static.geekmai.top/uPic/gtvTij.png)
预览
![tZO5Ib](https://static.geekmai.top/uPic/tZO5Ib.png)

**Comment by whyt-byte** [comment]
已有相应bug报告
https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/issues/42

后续找找原因

**Comment by emisjerry** [comment]
似乎是 .markdown-preview-view img, .markdown-preview-view video 裡的display:block 造成的。

**Comment by geekmai** [comment]
> 似乎是 .markdown-preview-view img, .markdown-preview-view video 裡的display:block 造成的。

改怎么修改啊

**Comment by whyt-byte** [comment]
问一下，你的系统是什么？我在win下无法复现，软件版本0.11.0

![image](https://user-images.githubusercontent.com/72023275/108229637-f24ccb80-717a-11eb-9851-00a5797b846b.png)

**Comment by emisjerry** [comment]
我目前是Windows 10, Obsidian 0.11.1 (0.11.0也不行)

測試字串：
```
用Mini Diary紀錄每天的美好🌼與心情😊👿😭👻
```

![image](https://user-images.githubusercontent.com/131511/108294346-a9bffd00-71d0-11eb-8818-1ee75fe93096.png)

**Comment by ddebby** [comment]
> > 似乎是 .markdown-preview-view img, .markdown-preview-view video 裡的display:block 造成的。
> 
> 是把 display:block 这行注释掉吗？

注释掉能够解决问题

**Comment by whyt-byte** [comment]
@emisjerry @ddebby @geekmai 
Done

谢谢
