### ISSUE TITLE
Simplicity(@Cuman)导致无法看清“Version History Diff”插件

### ISSUE THREAD

**Issue by shuojie819** [whyt-byte/Blue-Topaz_Obsidian-css#462]
> 当使用BT主题”Simplicity(@Cuman)”配色时，开启工作页面背景会导致“Version History Diff”插件显示看不清

![image](https://user-images.githubusercontent.com/72399630/204310539-d59ec6d7-2399-45a0-9820-19270936845b.png)

**Style Settings配置：**

```css
{
  "blue-topaz-theme@@color-scheme-options": "color-scheme-options-simplicity-topaz",
  "blue-topaz-theme@@background-settings-workplace-background-image": true
}
```

**Comment by cumany** [comment]
主题是哪个版本 更新到最新了吗

**Comment by shuojie819** [comment]
> 刚更新了版本，20221129

![image](https://user-images.githubusercontent.com/72399630/204433374-da92d23e-ed73-42ad-bee0-29a4c7855a3d.png)
