### ISSUE TITLE
Would you please add icon ahead of markdown file?

### ISSUE THREAD

**Issue by linfz94** [whyt-byte/Blue-Topaz_Obsidian-css#47]
Would you please add an icon ahead of markdown in the following version file like some other themes do, for examle below, it may help identify markdown file more efficiently.
![图片](https://user-images.githubusercontent.com/53118840/107944715-8bd47b80-6fc9-11eb-81ed-333ae73d7758.png)

**Comment by whyt-byte** [comment]
Sorry, I do not plan to add icons for .md files currently. All items are marked by a related file tag except for the .md files, thus, the .md file without an icon is itself an icon.

![image](https://user-images.githubusercontent.com/72023275/107951480-60ef2500-6fd3-11eb-9611-932bce87421e.png)
