### ISSUE TITLE
backslash後的字，如2\*3=6，在暗色主題下不清楚

### ISSUE THREAD

**Issue by Ali-C-Ila** [whyt-byte/Blue-Topaz_Obsidian-css#476]
如圖中的2\*3=6算式，backslash 很常被用來處理markdown中的星號(*)或其他符號，但backslash處理後的顏色太暗，在暗色主題很難看到。

是否可以根據深色/淺色主題調整預設顏色，或提供自訂選項?
![image](https://user-images.githubusercontent.com/56729449/207021408-f11b1d3a-6825-4c5f-9d02-e65ebc38e877.png)

**Comment by cumany** [comment]
更新主题应该 已经改善

**Comment by Ali-C-Ila** [comment]
大大的愛心❤️
