### ISSUE TITLE
This is not an issue request, but I'd like to ask a few questions on tweaking the css.

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#48]
If I'd like to change the background color of the line where the cursor is, which variable should I adjust?
BTW,
css 文件里好像有一大堆拼音缩写的颜色定义，是不是搞个注释？太难猜了 :D

**Comment by zhao414** [comment]
Oh, I have found it.

.theme-light .CodeMirror-activeline .CodeMirror-linebackground{
  background-color: #468eeb33 !important;
}

.theme-dark .CodeMirror-activeline .CodeMirror-linebackground{
  background-color: #468eeb33 !important;
}

**Comment by whyt-byte** [comment]
有空再说吧，一开始这个主题是自用的，所以有不少遗留问题，目前更新我都不能保证，没时间改注释或者改名字。

**Comment by whyt-byte** [comment]
改了
