### ISSUE TITLE
[外觀] tab標籤頁的標籤下突出了兩個角角

### ISSUE THREAD

**Issue by Ali-C-Ila** [whyt-byte/Blue-Topaz_Obsidian-css#481]
如圖，標籤頁的標籤下突出了兩個角角，這是原本的設計還是破圖啊?
鼠標位在出問題的右邊，鼠標不在的左邊看起來正常。
(似乎是最近1-2周的更新後才出現的)
(暗色模式，完全原始設定，有/無style settings都一樣)
![image](https://user-images.githubusercontent.com/56729449/208791946-a57bb2e3-b9c3-4f6d-9852-2bc8aadc4d88.png)

**Comment by cumany** [comment]
主题版本号是 是最新的主题吗

**Comment by Ali-C-Ila** [comment]
更新後已經消失了，謝謝!
