### ISSUE TITLE
Preview mode的list item沒有內縮

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#49]
list item在preview mode沒有內縮(Indent)？

▼ preview mode
![image](https://user-images.githubusercontent.com/131511/108599414-f6235c80-73cb-11eb-9f41-7748d6d71dbe.png)

▼ Edit mode 的list item有正確內縮
![image](https://user-images.githubusercontent.com/131511/108599440-18b57580-73cc-11eb-919f-bf90ab2bc30a.png)

**Comment by whyt-byte** [comment]
默认列表样式将会改成如下所示，将会在下个版本放出
![image](https://user-images.githubusercontent.com/72023275/108613805-56e48080-7430-11eb-81a1-a21823c7c974.png)
