### ISSUE TITLE
编辑模式下[]()形式链接鼠标悬停预览失效

### ISSUE THREAD

**Issue by Xianyu39** [whyt-byte/Blue-Topaz_Obsidian-css#495]
# 基本信息：
- OS：Windows 10
- Obsidian：1.0.3
- Blue Topaz：20230104
- Style Setting
```json
{
  "blue-topaz-theme@@color-scheme-options": "color-scheme-options-topaz-nord",
  "blue-topaz-theme@@toggle-calendar-shadow": true,
  "blue-topaz-theme@@toggle-calendar-transparent": true,
  "blue-topaz-theme@@style-options-for-calendar-plugin": "style-options-for-calendar-plugin-style-one",
  "blue-topaz-theme@@transparent-setting-panel": false,
  "blue-topaz-theme@@left-ribbon-style": "hide-left-ribbon",
  "blue-topaz-theme@@retain-header-color": false,
  "blue-topaz-theme@@loading-page-style-option": "loading-animation-cat"
}
```
# 详细信息
编辑模式下，按住Ctrl，鼠标悬停于`[xxx](xxx.md)`格式的链接上没有预览显示。
经过测试，这个问题和插件无关，在其他任何主题下、包括在预览模式下和`[[xxx]]`格式链接上都是正常的。

**Comment by hustrjh** [comment]
是的，我也测试了默认主题和其它几款主题，这种形式 **`[ ]( )`** 的链接都是可以在编辑模式下预览的。请 @whyt-byte 大大修复。感谢！

![image](https://user-images.githubusercontent.com/69783980/212647058-05f2cd96-7987-4930-9786-7edef03cc524.png)

**Comment by hustrjh** [comment]
@Xianyu39 我摸索了下，下方的CSS代码可以让超链接恢复正常，可以先用。

```
/* Ctrl+超链接 跳转、预览 */
body.link-click .cm-s-obsidian span.cm-link {
    pointer-events: auto !important;
}
```

**Comment by Xianyu39** [comment]
> @Xianyu39 我摸索了下，下方的CSS代码可以让超链接恢复正常，可以先用。
> 
> ```
> /* Ctrl+超链接 跳转、预览 */
> body.link-click .cm-s-obsidian span.cm-link {
>     pointer-events: auto !important;
> }
> ```

确实，已经解决了，谢谢大佬。

**Comment by hustrjh** [comment]
不客气哈~
实际上是Blue Topaz主题禁用的，我只是把它恢复回来。不知道禁用的原因是什么~ :face_exhaling: 
![image](https://user-images.githubusercontent.com/69783980/212797506-3b71fb0a-e80b-40a2-a511-c8c097400d05.png)

**Comment by cumany** [comment]
不需要这么麻烦  也不是什么主题bug
不喜欢的设置中取消即可
style setting 2.3.11 `取消编辑模式下点击链接自动跳转` 这个选项关闭即可。

**Comment by Xianyu39** [comment]
@cumany 原来如此，多谢解答。

**Comment by hustrjh** [comment]
@cumany  很棒！ :+1:
