### ISSUE TITLE
侧边栏宽度的问题

### ISSUE THREAD

**Issue by HueLiu** [whyt-byte/Blue-Topaz_Obsidian-css#5]
这个主题的左侧侧边栏如果拉的比较宽，显示效果会与其他主题不同，不确定是 feature 还是 bug。

**Comment by whyt-byte** [comment]
1. 为了多行显示；2. 也是为了让标题顺利换行而不是需要拖动水平滚动条。

所产生的bug是：拉动目录侧边栏在某些位置会显示异常、不停抖动。

但我觉得这个修改的好处更多（标题自动换行），所以姑且就这样了，等后面软件更新，我再看看有没有别的策略。
同样待解决的bug还有隐藏标题#所带来的定位问题。

**Comment by HueLiu** [comment]
好的感谢
