### ISSUE TITLE
Img grid doesn't work

### ISSUE THREAD

**Issue by Issam-seghir** [whyt-byte/Blue-Topaz_Obsidian-css#505]

**Comment by Issam-seghir** [comment]
![image](https://user-images.githubusercontent.com/74573675/214304239-523fd8d0-4888-4893-930b-d19436a30911.png)

>The same problem happens even if I use `cssclass: img-grid` or `!(img|+grid)[url]`

![gif](https://i.imgur.com/yDhuLqY.gif)

**Comment by cumany** [comment]
https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/blob/master/TIPS%20vault/TIPS%20for%20Blue%20Topaz_English.zip 
This is a tips vault with usage examples in it

**Comment by Issam-seghir** [comment]
I use the same methods mentioned in the tips vault but all of them doesn't work in my case 
So, I create a new vault and test the methods and all of them worked, so i concluded something wrong happen in my vault
After a long time of testing the new vault with all my plugins and a snippet, I discovered the problem, it's strange and unexpected!!

I compare the `community-plugins.json` in my new (test) vault and my actual vault and find that the sorting of community plugins is different, and the problem was the sorting of my community plugins in  the JSON file is not the same as in the obsidian GUI, ex:
![image](https://user-images.githubusercontent.com/74573675/214816249-35ad4f58-099d-42b3-88b6-425e72b46d4e.png)



![image](https://user-images.githubusercontent.com/74573675/214816429-7e6e466f-4fd8-41ef-9139-d447f9d1b862.png)

---
**Note that the first plugin is `admonition `but in the JSON file the first plugin is the `calendar `plugin**
**and the sort of plugins in obsidian does not match the JSON file** .

So, The solution is
- f your obsidian vault is open please close it before the do the next steps 
- creating a new vault 
- copy all you plugins to your new vault 
- open the new vault in obsidian 
- active all the plugins ( new obsidian automatically create the `community-plugins.json`
- copy the `community-plugins.json` to your actual vault 
- accept the message `Replace the file in the destination`
- restart obsidian and the image grid should work

now you can delete the new vault
