### ISSUE TITLE
Table row not displaying properly on hover

### ISSUE THREAD

**Issue by qazero** [whyt-byte/Blue-Topaz_Obsidian-css#525]
Screenshot without hover looks fine:

![image](https://user-images.githubusercontent.com/10906010/236352742-dac817de-9647-4641-8d19-9a3490869b51.png)

Screenshot with hover cuts cell in column 1:

![image](https://user-images.githubusercontent.com/10906010/236352838-32d3403b-4d1b-4b65-9165-78c8db280cba.png)

Markdown:

| Port | Protocol |
| ------------- |:---------------:|
| 21 | FTP |
| 22 | SSH |
| 23 | TELNET |
| 25 | SMTP |
| 53 | DNS |
| 80 | HTTP |
| 443 | HTTPS |
| 110 | POP3 |
| 143 | IMAP |
| 135 | MSRPC |
| 137 | NETBIOS |
| 138 | NETBIOS |
| 139 | NETBIOS |
| 445 | SMB |
| 3306 | MYSQL | 
| 1433 | MYSQL | 
| 3389 | RDP |
| 8080 | HTTP Proxy |

Raw markdown:

```
| Port | Protocol |
| ------------- |:---------------:|
| 21 | FTP |
| 22 | SSH |
| 23 | TELNET |
| 25 | SMTP |
| 53 | DNS |
| 80 | HTTP |
| 443 | HTTPS |
| 110 | POP3 |
| 143 | IMAP |
| 135 | MSRPC |
| 137 | NETBIOS |
| 138 | NETBIOS |
| 139 | NETBIOS |
| 445 | SMB |
| 3306 | MYSQL | 
| 1433 | MYSQL | 
| 3389 | RDP |
| 8080 | HTTP Proxy |
```

**Comment by whyt-byte** [comment]
Please update the theme. Or you may cancel the zooming effect in Style Settings, as shown below:
![image](https://user-images.githubusercontent.com/72023275/237019701-b592513d-0a86-46c8-9a0f-b86fd0498359.png)

**Comment by qazero** [comment]
As suggested, I updated the theme just now but it didn't fix the issue. Disabling the Table Zoom Effect in the settings worked. However, it would be nice to have this setting enabled without cutting off the text as it is a very nice feature. Is there any way you can make it zoom less or have it zoom the same amount without cutting off the text?

**Comment by qazero** [comment]
Just following up in regards to my previous message. Would something like that be possible as mentioned in my last message?
