### ISSUE TITLE
增加 stacked tabs 中调整标题栏和页面宽度的选项

### ISSUE THREAD

**Issue by yett1873** [whyt-byte/Blue-Topaz_Obsidian-css#527]
如图是minimal theme的设置，好馋这个功能，希望能够在blue topaz中实现~

![image](https://user-images.githubusercontent.com/75569851/236694836-995856b7-d656-447c-8572-2151640a17f4.png)

**Comment by whyt-byte** [comment]
已经在新更新中加了这个选项，Style Settings 2.3.26。Enjoy!
