### ISSUE TITLE
note lists indention are disordered after moving notes from one folder to another

### ISSUE THREAD

**Issue by volksvagen** [whyt-byte/Blue-Topaz_Obsidian-css#529]
This bug only happens in several themes, including this one

## to reproduce:

before a note is moved:

![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/30553808/f3ff356f-ac27-4a6c-a991-6f0698937127)

move note a from folder 1 to folder 2:

![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/30553808/619ddb35-f7dd-472c-abfa-2a17b350c538)

## issue description

after moving, an unexpected indentation occurs in the destination folder.

click 'collapse all' and 'expand all', the indentation restores to normal state:

![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/30553808/d92fd5e6-7735-47d4-abfc-cb73eed91485)

![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/30553808/861c090f-5c6e-4022-8cbe-b3920600d928)

![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/30553808/ee1fb16c-940d-4df3-88c9-3d253765b3c5)

further more, this bug will not happen until Obsidian is reopened and switch the themes.

**Comment by Ali-C-Ila** [comment]
This is not a bug. Obsidian adds a "1" after any duplicated file name in the same folder, so as to avoid confusion for wiki links, quick switcher, etc. 

(Please to think before your post: have you tried this without the theme on?)

**Comment by volksvagen** [comment]
@Ali-C-Ila Sorry for the bothering, what you are telling is true.

I was distracted by the above action by Obsidian.

To correct this, I repost the issue.
