### ISSUE TITLE
the folding arrow vanished

### ISSUE THREAD

**Issue by jljovano** [whyt-byte/Blue-Topaz_Obsidian-css#532]
Hello, I use and love the theme Blue Topaz, but (once again) the folding arrow that collapse the documents in folders has disapeared.

https://i.imgur.com/vCSS8gQ.png

Any way (CSS ? Others) to get it back until the theme is updated ?

Thank you

**Comment by Boingo100p** [comment]
Same. I just managed to work around this issue by adjusting settings under "2.3.3 folder" (style settings plugin) to use folder icon instead of arrow.

**Comment by jljovano** [comment]
Thank you, it works quite nicely ;)
 
 
 
-----E-mail d'origine-----
De: Boingo100p ***@***.***>
A: whyt-byte/Blue-Topaz_Obsidian-css ***@***.***>
Cc: jljovano ***@***.***>; Author ***@***.***>
Envoyé le: Me, 31 Mai 2023 3:46
Sujet: Re: [whyt-byte/Blue-Topaz_Obsidian-css] the folding arrow vanished (Issue #532)

Same. I just managed to work around this issue by adjusting settings under "2.3.3 folder" (style settings plugin) to use folder icon instead of arrow.—

**Comment by whyt-byte** [comment]
Fixed by @cumany #535
