### ISSUE TITLE
1.3.3版之后文件树的箭头不显示

### ISSUE THREAD

**Issue by BetterYimi** [whyt-byte/Blue-Topaz_Obsidian-css#533]
<img width="33" alt="image" src="https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/59110457/e5f9435a-679d-42dc-bd2c-ab0d8bfff4e0">

**Comment by jocundmo** [comment]
same issue

**Comment by Boingo100p** [comment]
Same. I just managed to work around this issue by adjusting settings under "2.3.3 folder" (style settings plugin) to use folder icon instead of arrow. 
相同问题。刚试了下，使用文件夹图标取代箭头图标可以绕过这个问题。在 style settings 插件的“2.3.3 folder”下配置。

**Comment by AriaLyy** [comment]
感觉这个主题，没次升级版本都会出现这个问题

**Comment by whyt-byte** [comment]
> 感觉这个主题，没次升级版本都会出现这个问题

不是主题出问题，而是每次软件更新，主题都会受伤。我1.2.8才改好树状结构，他们1.3就又改了，很烦人的

**Comment by whyt-byte** [comment]
#535

**Comment by AriaLyy** [comment]
ob这升级确实烦人~~
