### ISSUE TITLE
點擊Emoji 文字變成預覽

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#55]
Hover to Emoji文字會是放大鏡圖示，點擊後會預覽。如下圖，點擊Emoji文字後想要跳到 ^toc 區塊位置，試了別的主題可以正常運作。

因為Emoji文字就一個字元大小，預覽沒什麼用處，能否不要預設變成預覽？

![image](https://user-images.githubusercontent.com/131511/110902439-dd5df500-8340-11eb-9365-a2889cd9ff2e.png)

**Comment by whyt-byte** [comment]
Done
