### ISSUE TITLE
编辑模式下，在引用内容中选择最后一行，光标错位

### ISSUE THREAD

**Issue by hxhc** [whyt-byte/Blue-Topaz_Obsidian-css#6]
我用的是Asymmetric Blue Topaz 0.9.3，谢谢作者的分享，这个主题最喜欢了。

光标错位的问题在标题中已经没有问题，可是在引用内容中仍存在，比如选择最后一行时无法全部选择，最后一点内容总是无法选中，如下图所示。

![img](https://i.loli.net/2020/10/19/BiwuMLT7Rtvk356.png)

**Comment by hxhc** [comment]
还有就是最后那个 [^2] 的footnote没有正常渲染，不过前一个[^1]是渲染成蓝色了

**Comment by whyt-byte** [comment]
光标错位问题都是因为隐藏或者大幅改变符号大小导致的，Asymmetric Blue Topaz明亮模式没有光标错位是因为不再隐藏#（黑暗模式依旧隐藏#，还是会错位，所以名字叫“asymmetric”）。但是引用框做了伪即时渲染处理，隐藏了">"，所以在目前版本下，必然会导致光标错位，现在没有解决办法，只能将就着用，或者完全摈弃。

脚标那个是我觉得是软件的事，你可以把自定义主题的选项关了，看看是不是也是这样，如果是，那就不是我的锅了😁。

**Comment by hxhc** [comment]
> 
> 
> 光标错位问题都是因为隐藏或者大幅改变符号大小导致的，Asymmetric Blue Topaz明亮模式没有光标错位是因为不再隐藏#（黑暗模式依旧隐藏#，还是会错位，所以名字叫“asymmetric”）。但是引用框做了伪即时渲染处理，隐藏了">"，所以在目前版本下，必然会导致光标错位，现在没有解决办法，只能将就着用，或者完全摈弃。
> 
> 脚标那个是我觉得是软件的事，你可以把自定义主题的选项关了，看看是不是也是这样，如果是，那就不是我的锅了😁。

试了一下，角标确实是软件的问题；主题问题也是个小问题，目前没有解决方法也没事，毕竟太好看了

**Comment by whyt-byte** [comment]
谢谢你的肯定。如果受不了光标错位，可以手动删除或者注释掉（/* */）1115-1207行（黑暗模式的#隐藏），1576-1584行（引用框的伪即时渲染）。

P.S. 所指行数只对应20201018版本的Asymmetric Blue Topaz；版本更新了，css也要更新了，这两天会更新，也请继续关注。
