### ISSUE TITLE
The color issue in mermaid gantt graph

### ISSUE THREAD

**Issue by linfz94** [whyt-byte/Blue-Topaz_Obsidian-css#61]
dear developer, sorry to bother, i find an issue about color scheme in gantt graph, when an task with "crit" status, its background is black, thus the label of this task will be overshadow. There are the code.
```mermaid
gantt
    title 周计划
	dateFormat E
	axisFormat %a
	section 班表
	Task :d1, 2, 12h
	CTR(11*) :after d1, 12h
	CTR(14) :d2,3,12h
	夜班 :after d2,12h
	休息: d3, 4, 12h
	ToDo: after d3, 12h
	DRT :d4,5,12h
	CTR(45) :after d4,12h
	section 写作
	修缮 : crit, 1,3
	申请 : crit, 3,5
	提交 : crit, 5,6
	section 其他
	寄送审核 : 1,4
	section 放假
	去找Robert : 1,2
```
![图片](https://user-images.githubusercontent.com/53118840/113379231-854c6880-93ab-11eb-9791-33b1ac0cdfac.png)

**Comment by whyt-byte** [comment]
Hi linfz94, thank you for reporting. 
I have fixed this. Enjoy!
