### ISSUE TITLE
代码块里的选中和对齐有问题

### ISSUE THREAD

**Issue by CapZhang** [whyt-byte/Blue-Topaz_Obsidian-css#62]
1. 代码块里的选中第一行会有一点padding
2. 代码块里的选中在很窄的时候尾巴没有全覆盖代码
![image](https://user-images.githubusercontent.com/19522615/113398126-ab383400-93d0-11eb-956e-13e5ac6bca8b.png)
![image](https://user-images.githubusercontent.com/19522615/113398168-bd19d700-93d0-11eb-8c31-7f4a04144425.png)

3. 渲染出来的代码第一行会有一个padding
![image](https://user-images.githubusercontent.com/19522615/113398228-cf941080-93d0-11eb-951f-2f23e204a6f9.png)

原始主题没有问题，使用您的主题会有以上三个对不齐的问题，我没有能力自己解决。。大佬能帮我看下吗

假如我想使用原来的代码块的css，需要注释那部分内容呢

**Comment by linfz94** [comment]
此外，文本的两端对齐是不是也失效了？
![图片](https://user-images.githubusercontent.com/53118840/113468884-ada39800-947b-11eb-82a3-68150c169c41.png)

**Comment by whyt-byte** [comment]
![image](https://user-images.githubusercontent.com/72023275/113481303-56c5af00-94cb-11eb-999f-a11fe630691c.png)
无法复现，请检查设置：

1. 关闭该选项
![image](https://user-images.githubusercontent.com/72023275/113481272-25e57a00-94cb-11eb-893e-e806d9e0cdb6.png)

2. 更新主题

---

我对代码框改动很多，恕我无法一一指出。

**Comment by whyt-byte** [comment]
> 此外，文本的两端对齐是不是也失效了，2.2版本的是没有问题的。
> ![图片](https://user-images.githubusercontent.com/53118840/113468884-ada39800-947b-11eb-82a3-68150c169c41.png)

![image](https://user-images.githubusercontent.com/72023275/113481550-c2f4e280-94cc-11eb-9a52-8b650feee502.png)
无法复现，请检查设置
