### ISSUE TITLE
表格编辑感觉需要优化

### ISSUE THREAD

**Issue by zhl111** [whyt-byte/Blue-Topaz_Obsidian-css#63]
表格一旦文字偏长，就会被隐藏不显示，又不能换行，编辑起来很不方便，恳请优化一下？非常感谢

**Comment by whyt-byte** [comment]
麻烦确定默认主题的是什么样，再截图，节省沟通时间

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/113796061-ef388980-9780-11eb-8469-be0dccc54089.png)
主题就是您的blue主题，解决办法就是取消缩减栏宽选项吗？但除了表格外，缩减栏宽比较适用

**Comment by whyt-byte** [comment]
Done
