### ISSUE TITLE
 Text justify-align failed when Readable line length is disable

### ISSUE THREAD

**Issue by linfz94** [whyt-byte/Blue-Topaz_Obsidian-css#64]
Hi there, I found a bug here, when Readable line length is disable, the text justify-align just failed, all the text turn right-align in both editing mode and preview model. 
![图片](https://user-images.githubusercontent.com/53118840/114838043-e68e2600-9e06-11eb-838d-bcd36e981926.png)
And by using the css snippet below justify-align can be recover, but what I want is justify-align in preview mode but right-align in editing mode, I am not proficient in css, can you please tell me how to achieve by css snippet.
```
.cm-s-obsidian,
.markdown-preview-view {
    text-align: justify;hyphens: auto;
}
```

**Comment by whyt-byte** [comment]
Hi! Please create a css snippet and copy the following code
```css
.markdown-source-view.is-readable-line-width .CodeMirror {
  text-align: right;
}
```
