### ISSUE TITLE
Quoting a line with a link causes vertical quotation line to disappear

### ISSUE THREAD

**Issue by andrew-nguyen** [whyt-byte/Blue-Topaz_Obsidian-css#65]
The following raw markdown:

```
>here is a quoted line
>https://www.google.com
>another quoted line
```

results in:

![image](https://user-images.githubusercontent.com/901859/115797454-d1764180-a388-11eb-9d66-b32fee849419.png)

though it renders as expected:

![image](https://user-images.githubusercontent.com/901859/115797480-dfc45d80-a388-11eb-8cf2-183ff84e4ed1.png)

**Comment by whyt-byte** [comment]
Fixed. Thank you.

**Comment by whyt-byte** [comment]
![image](https://user-images.githubusercontent.com/72023275/142452290-51f7b5f4-f444-4b15-89ef-85ea5801d005.png)

A very late reply...

Now Obsidian has fixed it!
