### ISSUE TITLE
使用蓝色 Topaz 主题时在笔记中显示为灰色

### ISSUE THREAD

**Issue by zhl111** [whyt-byte/Blue-Topaz_Obsidian-css#66]
[Black or red fonts appear grey in the notes when using the Blue Topaz theme · Issue #15 · zsviczian/obsidian-excalidraw-plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/15#event-4646039592)
g text{
  fill:var(--text-muted) !important;
}

#arrowhead,  #sequencenumber,  .cluster text,  .label text,  text,  text.actor {
  fill:var(--text-muted) !important;
}

**Comment by whyt-byte** [comment]
Done
