### ISSUE TITLE
Onsidian Android的bullet symbol太靠近文字

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#67]
Android 0.18版箭頭符號太接近文字，不知能否改善?  似乎桌面版以前我也回報一次，該次是把Obsidian.css刪掉，改用themes裡的才正常。

![image](https://user-images.githubusercontent.com/131511/117231233-65e4a780-ae51-11eb-9316-b21273c362bf.png)

**Comment by whyt-byte** [comment]
Done
