### ISSUE TITLE
文内链接小窗口BUG

### ISSUE THREAD

**Issue by sunyyo** [whyt-byte/Blue-Topaz_Obsidian-css#68]
文内链接[[ ]]小窗口有个BUG，有2个滚动条，鼠标滚轮拉不到底，要拖动其中一个才能滚动到底部。

mermaid格式，中文字体和文章字体不统一。

**Comment by whyt-byte** [comment]
mermaid字体就是那样设置的，可以自行更改

**Comment by whyt-byte** [comment]
(Popover) Fixed
