### ISSUE TITLE
css样式会导致一个第三方插件的布局重叠

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#70]
启用 Blue-Topaz 样式后，会导致  Markdown Formatting Assistant 插件的布局重叠，如图
![121792357-51e94e00-cc26-11eb-9a14-84d10e701c3d](https://user-images.githubusercontent.com/56058332/121798019-6e04e380-cc56-11eb-9783-a75593e74ec5.png)

而在系统默认样式下则不会，
![Snipaste_2021-06-13_14-43-48](https://user-images.githubusercontent.com/56058332/121798027-7a893c00-cc56-11eb-9835-704184074119.png)

**Comment by whyt-byte** [comment]
Done
