### ISSUE TITLE
标题与文本内容过近

### ISSUE THREAD

**Issue by sunyyo** [whyt-byte/Blue-Topaz_Obsidian-css#74]
![1](http://obsidian87.oss-cn-qingdao.aliyuncs.com/1627962854612.png)

跟表格交叉了

**Comment by whyt-byte** [comment]
是的，已经有人报告了这个问题。我会尽快修复，抱歉这个问题对你的使用造成了困扰

**Comment by whyt-byte** [comment]
已修复，请更新。
