### ISSUE TITLE
已经安装了霞鹜文楷，为什么字体变不过来呢？

### ISSUE THREAD

**Issue by wanghusw** [whyt-byte/Blue-Topaz_Obsidian-css#75]
如题，需要进行什么设置吗？

**Comment by wanghusw** [comment]
在 `GitHub` 下载了最新的文件，可以正常显示了，标题和正文距离太紧，快挤在一起了呢。

**Comment by whyt-byte** [comment]
是的，前几天就有人报告这个问题，因为很忙，到现在都没有修复。只能说声不好意思，我会尽快修复

**Comment by whyt-byte** [comment]
> 在 `GitHub` 下载了最新的文件，可以正常显示了，标题和正文距离太紧，快挤在一起了呢。

已修复，请更新
