### ISSUE TITLE
长图以及pdf无法下拉

### ISSUE THREAD

**Issue by sunyyo** [whyt-byte/Blue-Topaz_Obsidian-css#76]
单张长图文件，PDF文件，鼠标滚轮下拉没反应，右边的滚动条也拖不动

**Comment by whyt-byte** [comment]
win 10无法复现，请提供你的使用平台

**Comment by sunyyo** [comment]
!(http://obsidian87.oss-cn-qingdao.aliyuncs.com/%E6%8D%95%E8%8E%B7.JPG)

win10笔记本，这种巨图，主题的背景图片好像压住它了

**Comment by whyt-byte** [comment]
找到问题在哪了，谢谢反馈

**Comment by whyt-byte** [comment]
已修复
