### ISSUE TITLE
关于表格的问题

### ISSUE THREAD

**Issue by pikawindy** [whyt-byte/Blue-Topaz_Obsidian-css#78]
我在用dataview创建表格时发现，如果单元格名字过长，表格里面的空隙就特别大，很不紧凑也不雅观，在用原生主题是没这个问题的，请问有什么办法解决吗

**Comment by whyt-byte** [comment]
请麻烦截图说明

**Comment by pikawindy** [comment]
![](https://cf-ipfs.com/ipfs/QmTiWKtPBdFU2Wxgc7VQcjJdarhXruXsGZdjbVY1ZxgATa)

这样

**Comment by whyt-byte** [comment]
好的，谢谢提供截图。我微调了一下表格，请更新看看

**Comment by pikawindy** [comment]
> 好的，谢谢提供截图。我微调了一下表格，请更新看看

太感谢了，已经可以了，谢谢

**Comment by whyt-byte** [comment]
没事，客气了
