### ISSUE TITLE
在 Obsidian Publish 中 使用暗黑模式, 文字显示为黑色, 难以辨认 

### ISSUE THREAD

**Issue by AntoineChn** [whyt-byte/Blue-Topaz_Obsidian-css#79]
作者你好, 

我使用 这款主题已经很长时间了, 感觉非常棒, 尤其是 列表的设计, 十分易读.
于是我想在 Obsidian Publish 使用这一款主题. 

为了能够获得 彩色的 标题 (Headers). 我尝试将 Obsidian Publish 设置为暗黑模式. 
接着, 我不理解的问题便出现了: 同样的 css 更名为 publish.css 并发布到网站上之后, chrome 中呈现的效果却是 暗黑主题 + 黑色的主体文字 (Text body). 阅读起来十分困难.

另外, 还会出现 明亮主题 与 暗黑主题 混合的情况 (见 下面的截图)

![Screenshot 2021-08-11 at 21 51 18](https://user-images.githubusercontent.com/17791254/129094712-e1b721b6-4b87-4cf4-bdc7-5037b5ffe51d.png)

请问 这个问题好解决么 ? 

提前感谢

**Comment by AntoineChn** [comment]
上面截图中页面的地址:  https://publish.obsidian.md/antoinechn/Wiki+Notes/A+probabilistic+view+of+common+logic+syllogisms+%E4%BB%8E%E6%A6%82%E7%8E%87%E8%A7%92%E5%BA%A6%E7%9C%8B%E5%B8%B8%E8%A7%81%E9%80%BB%E8%BE%91%E6%8E%A8%E6%96%AD

**Comment by whyt-byte** [comment]
谢谢反馈，我大概知道是哪里的问题，但是手上没有publish服务，之后改完得麻烦你看一下是否正常了

**Comment by AntoineChn** [comment]
好的, 谢谢 🙏

**Comment by AntoineChn** [comment]
作者你好. 我刚刚从 GitHub 下载了最新的  commit `62aa9df` 版本的主题. 并且尝试上传到 我的 Obisidian Publish 上. 本条 Issue 中提到的问题 已经基本解决了. 我目前只观察到一个小问题:

- [ ] Publish 版本 的 加粗文字 (`**`) 仍然显示为黑色. 但是 这个主题 在 本地版 Obsidian 就没有这个问题. (见截图 红笔圈出的文字)

请问 这个问题方便解决么?

![Screenshot 2021-08-22 at 13 22 32](https://user-images.githubusercontent.com/17791254/130353411-35ddac5a-7c33-440f-ab05-8ff5c2999e46.png)

**Comment by whyt-byte** [comment]
刚想问一下修复情况，谢谢你的快速反馈。这个地方我遗漏了，之前是为了导出pdf做的设置，跟publish冲突了，不好意思，晚点我会修复这个问题。

**Comment by AntoineChn** [comment]
> 刚想问一下修复情况，谢谢你的快速反馈。这个地方我遗漏了，之前是为了导出pdf做的设置，跟publish冲突了，不好意思，晚点我会修复这个问题。

好嘞, 太客气啦, 你的主题超级棒 (尤其是 列表的样式, 和 Header 的配色 十分醒目 容易阅读), 谢谢你才是 😄.

**Comment by whyt-byte** [comment]
谢谢夸奖，我很高兴😸
已经进行修复，如果有时间的话，请反馈一下是否正常。

**Comment by AntoineChn** [comment]
> 谢谢夸奖，我很高兴😸

值得高兴, 哈哈

> 已经进行修复，如果有时间的话，请反馈一下是否正常。

好的, 我刚刚 测试了一下, 问题完美解决👍 (如图) 再次感谢😁. 

![Screenshot 2021-08-22 at 23 13 00](https://user-images.githubusercontent.com/17791254/130370262-010be947-eb63-4f86-a2cb-defe39a94d29.png)
)
