### ISSUE TITLE
為何中文字自動伸展到右邊界?

### ISSUE THREAD

**Issue by emisjerry** [whyt-byte/Blue-Topaz_Obsidian-css#81]
圖中是兩行文字，但第一行右側的中文字卻自動充填空白？如何取消自動充填機制? 
![image](https://user-images.githubusercontent.com/131511/129523761-d749f6fa-d50f-45c7-abc0-013c782c8757.png)

Thanks.

**Comment by whyt-byte** [comment]
对齐已处理为默认左对齐
