### ISSUE TITLE
关于 Demonstration_TIPS_for_Blue-Topaz

### ISSUE THREAD

**Issue by pikawindy** [whyt-byte/Blue-Topaz_Obsidian-css#82]
请问您这demo中关于图片并排展示的例子是不是弄错顺序了？
![](https://cf-ipfs.com/ipfs/QmPz8aLas5oSozDmTsT9k3ZThwaQ88xWzQ1M7jeyAfdv4Q)

Method 1 说的是只要这样 ![[xxx.png|+grid]] 并且 在同一行就能图片并排展示，但点进去看demo却发现yaml有cssclass: img-grid字段;
而Method 1 刚好调过来 ，是我理解错了吗？

**Comment by whyt-byte** [comment]
啊，大意了，的确如你所说。我会改一下这两个顺序。方法是没错的，只是我排序的问题。谢谢反馈了
