### ISSUE TITLE
Dark mode下进行publish或者输出pdf的时候，变成了白色背景

### ISSUE THREAD

**Issue by preminstrel** [whyt-byte/Blue-Topaz_Obsidian-css#88]
Dark mode下进行publish或者输出pdf的时候，变成了白色背景。
publish的官网提供的付费服务，export pdf是内置的功能。
Thanks for your time!

**Comment by whyt-byte** [comment]
pdf都是默认白色背景。publish的颜色你更新一下试试，你主题版本可能过低

**Comment by preminstrel** [comment]
谢谢！是版本的原因。
Thanks for your time!
