### ISSUE TITLE
在无序列表下 使用双美元符号插入行间公式. 在预览中 这个公式并不居中. 有序列表下无此问题

### ISSUE THREAD

**Issue by AntoineChn** [whyt-byte/Blue-Topaz_Obsidian-css#89]
## 问题描述

作者你好, 

如题, 在无序列表下 使用双美元符号 插入行间公式. 预览模式下 公式无法居中. 这个问题在 有序列表下并不存在. 请问这个是普遍问题么?

提前感谢.

### Code

```markdown
### 无序列表的例子

- 补运算 封闭性
    $$\forall ~ A\in\mathcal{F},\quad A^\complement \in \mathcal{F}$$

***

### 有序列表的例子

1. 补运算 封闭性
    $$\forall ~ A\in\mathcal{F},\quad A^\complement \in \mathcal{F}$$
```

### Preview

<img width="2040" alt="Screenshot 2021-09-24 at 19 04 45" src="https://user-images.githubusercontent.com/17791254/134713792-02b6b094-a030-4921-98ac-b5836d22573a.png">

**Comment by whyt-byte** [comment]
你好，我直接粘贴了你提供的文字，没有复现你的问题，如下图所示。你可以：1. 更新主题（看你图中颜色，不是最新版主题）；2. 关闭片段与插件进行排查。如果是片段导致的，请告诉我，我会进行修复（看你用的片段，你应该是在群里吧）
![image](https://user-images.githubusercontent.com/72023275/134755986-07c67fc9-e7e4-481a-bf56-662ceecd2d0f.png)

**Comment by AntoineChn** [comment]
你好. 果然, 更新了主题 (覆盖本地版本) 问题就解决了. 

我想是因为 : 我更习惯于 无衬线字体 (对我来说, 更易于阅读) 于是自己尝试替换 CSS 中   /*font family*/ (已发布版本444行) 的内容. 这期间可能搞砸了. 自己制定过 CSS 后, 也没有 跟进 主题的新版本发布. 才出了这样的问题. 

现在都解决啦, 感谢你的回复. 

PS. 你指的哪一个群? 一个单独的 计算机/数学方向的 学习小组么? 
我目前只在 官方Discord 与 QQ群 里. 但是 QQ群 信息流太大, 我没怎么关注过.

**Comment by whyt-byte** [comment]
好的，解决就好，最好用片段的方式进行自定义修改，方法见：https://forum-zh.obsidian.md/t/topic/180

群指的是QQ群（908688452），因为你在标题前显示的H3很像我在群里放出的片段。群是个用户内测群，提供一些片段并解决部分需求。
