### ISSUE TITLE
预览模式代码没有行号，编辑模式代码没有高亮。

### ISSUE THREAD

**Issue by kingname** [whyt-byte/Blue-Topaz_Obsidian-css#9]
编辑模式：

![image](https://user-images.githubusercontent.com/5440523/98439480-184ee280-212d-11eb-855e-dee06337e01f.png)

预览模式：

![image](https://user-images.githubusercontent.com/5440523/98439494-2dc40c80-212d-11eb-9721-35c1a2c47f1b.png)

期望编辑模式启动代码高亮，预览模式显示代码行号。

**Comment by whyt-byte** [comment]
软件在编辑模式下高亮，可以使用插件
![image](https://user-images.githubusercontent.com/72023275/98442798-f875e980-2141-11eb-9a9a-48d6d3630c1b.png)

软件目前做不到预览模式显示行号，建议去官方论坛提出你的需求。
