### ISSUE TITLE
to recall

### ISSUE THREAD

**Issue by Jacobxz** [whyt-byte/Blue-Topaz_Obsidian-css#91]
能不能把to recall 放到一行使用，这样好像不行，改了半天没改出来，hhh
![image](https://user-images.githubusercontent.com/48195963/136164113-7c70dc5a-0852-4838-b7a7-5a341ec465f4.png)
![image](https://user-images.githubusercontent.com/48195963/136164169-9913c97a-cb2e-449f-95b2-fb8a64244b2d.png)
放到一行后
![image](https://user-images.githubusercontent.com/48195963/136164246-3ddd6b49-3a43-4469-9bdc-f9f68962c8d3.png)
![image](https://user-images.githubusercontent.com/48195963/136164298-7603fe75-e4a3-4762-9ad6-1055015a9f6b.png)

**Comment by whyt-byte** [comment]
不好意思，教程写的大意了，你把`<p class="to-recall"\>`里面的`\`删掉就行了
