### ISSUE TITLE
left sidebar serif fonts

### ISSUE THREAD

**Issue by yejzh** [whyt-byte/Blue-Topaz_Obsidian-css#92]
from the screenshot, left sidebar should display san-serif fonts, but in my case (Mac m1, Big Sur 11.6), it displays serif fonts, I can't figure out what causes this problem, so please fix it, or give us some hint how we can customize font setting for that part

**Comment by whyt-byte** [comment]
I cannot reproduce the bug you reported. Maybe you can fix it by updating your theme. 
And you can create a CSS snippet as shown below to change the font family 
```css
:root {
--font-family-folder-file-title: ;
}
```
