### ISSUE TITLE
Linked note text disappeared when export to pdf

### ISSUE THREAD

**Issue by Jason11ookJJ** [whyt-byte/Blue-Topaz_Obsidian-css#93]
# pdf text
![image](https://user-images.githubusercontent.com/50993239/137632464-5630cee8-99cf-4cc1-8006-507142dd4551.png)

# original text
![image](https://user-images.githubusercontent.com/50993239/137632485-d2c1f692-a650-4213-9718-3293a5c2854a.png)

_It is on the newest version, but I like the old font more, so I changed it_

**Comment by whyt-byte** [comment]
I think now it's okay for the latest version (insider). If yes, I will close this issue.

**Comment by Jason11ookJJ** [comment]
You can close it, as the bug is not on your side

在 2021年11月18日週四 23:42，whyt-byte ***@***.***> 寫道：
