### ISSUE TITLE
tag 中包含 下划线 "_" (例如 xxx_xxx) 时, 编辑页面 不能正确显示背景颜色, 阅览页面无此问题

### ISSUE THREAD

**Issue by AntoineChn** [whyt-byte/Blue-Topaz_Obsidian-css#96]
作者你好, 

如题, 当tag 包含 下划线 `_` 例如 `xxx_xxx`, 在编辑页面 不能正确显示背景颜色. 

下图所示,

<img width="1094" alt="Screenshot 2021-10-24 at 19 21 05" src="https://user-images.githubusercontent.com/17791254/138605383-8999125c-f7e9-4590-a93f-1f563e16c59a.png">

请问这个问题可以解决吗? 

提前感谢

Antoine

**Comment by whyt-byte** [comment]
已修复，谢谢反馈
