### ISSUE TITLE
文件夹的样式怎么弄的？

### ISSUE THREAD

**Issue by liba36** [whyt-byte/Blue-Topaz_Obsidian-css#97]
不好意思，刚开始用obsidian，请问下面这个左边文件夹的样式怎么弄的？谢谢！

![image](https://user-images.githubusercontent.com/72023275/134859577-ca6bf35a-6a6a-45b1-ba0e-5aca7a4c4990.png)

**Comment by whyt-byte** [comment]
QQ群里提供的片段
