### ISSUE TITLE
文件夹大纲线相对箭头偏移了约1像素

### ISSUE THREAD

**Issue by umenemu133** [whyt-byte/Blue-Topaz_Obsidian-css#99]

**Comment by umenemu133** [comment]
![image](https://user-images.githubusercontent.com/35651019/140318117-257f7548-dc59-4112-a0ec-d2c0cb5edff9.png)
箭头和大纲线轻微地没有对齐，不知道是否是我的显示器的问题。

**Comment by whyt-byte** [comment]
已优化，谢谢反馈
